### ISSUE TITLE
morepath (autosetup) failed in when run inside PyCharm

### ISSUE THREAD

**Issue by berndca** [morepath/morepath#176]
I'm using PyCharm, Everything went well with the very basic introductory example. However when I switched to morepath.autosetup() all I got was 404's and stacktraces. The server log did not show any issues before the first get.

> Here is the traceback:
> Traceback (most recent call last):
>   File "C:\Python27\Lib\wsgiref\handlers.py", line 85, in run
>     self.result = application(self.environ, self.start_response)
>   File "C:\Users\Bernd\morepath\lib\site-packages\morepath\app.py", line 123, in __call__
>     return self.mounted(environ, start_response)
>   File "C:\Users\Bernd\morepath\lib\site-packages\morepath\mount.py", line 36, in __call__
    response = self.app.publish(request)
  File "C:\Users\Bernd\morepath\lib\site-packages\morepath\publish.py", line 65, in publish
    return resolve_response(request, model)
  File "C:\Users\Bernd\morepath\lib\site-packages\morepath\publish.py", line 47, in resolve_response
    raise HTTPNotFound() 

Please advise.

Thanks, Bernd

**Comment by faassen** [comment]
I think we've improved the situation quite a bit now, especially with Dectate.
