### ISSUE TITLE
tutorial/demo/cool applications for Morepath

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#199]
There are a number of reasons why we'd want to build applications in Morepath:

* as a tutorial, probably in combination with a tutorial app. We need a widely well understood app for that; todo app, blog, activity stream. The app itself is not intended to be deployed but only to demonstrate the capabilities and be useful for learning.

* as a way to impress users: wow, you can build this with this framework? that's amazing. This app might do something new and unusual, meaning it's less likely to be a good tutorial app. This can be combined with...

* a useful app for users, like a Django admin UI. a tutorial might exist how you can expand this so you can use the UI for new purposes. shouldn't have massive scalability requirements

**Comment by andrss** [comment]
On the issue of cool applications for Morepath let me introduce damvitool - Sandman inspired database and schema agnostic automatic REST API creator and data viewer/analyser. Questions, comments, critique are welcome. Thank you, Martijn, for providing such a wonderful tool!
Github repo can be found here: https://github.com/praxigento/damvitool

**Comment by faassen** [comment]
Wow, thanks @andrss! I'm traveling a lot recently but I'll try to give this a shot soon! Do you mind some feedback/questions on the Morepath code?
