### ISSUE TITLE
document how to write a test for an existing morepath app

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#203]
This is slightly different from testing Morepath itself, which is what most of Morepath's tests are doing. It involves setting up Morepath when the test starts (or in a fixture), and then using webtest to interact with it.

**Comment by faassen** [comment]
We should include a test that checks for permission.

**Comment by faassen** [comment]
Where in the documentation should this go? I think a new document, testing.rst, inserted just after organizing_your_project in toc.rst.

**Comment by faassen** [comment]
@taschini would you be interested in looking into this? Note that we should document the basic scenario without permission checks first. Permission checks just demonstrate a bit more involved setup and exercise webtest a bit more too, so that should definitely be in another section of the document. Just having the basic scenario documented would be a great first step though.

**Comment by taschini** [comment]
I can give it a shot.

**Comment by faassen** [comment]
Yay, this is in there now, thanks @taschini!
