### ISSUE TITLE
Class-based views

### ISSUE THREAD

**Issue by href** [morepath/morepath#257]
I was wondering if it was a good idea to allow views to be classes. Currently, only functions are allowed. Is there a reason why the following shouldn't work in Morepath?

```python
@App.view(path='', model=Document)
class DocumentView(object):
    def __init__(self, model, request):
        self.model = model
        self.request = request

     def __call__(self):
        return self.request.link(self.model)
```
This could of course be done by the function instead, but the same could be said for the path directive, where classes work.

I know other frameworks provide both ways, so you can choose functions or classes depending on your own preferences. Would this make sense for Morepath?

**Comment by faassen** [comment]
I needed to get back to this sooner, sorry about that. I think we need to wait and see what happens here -- I can see there are use cases for class-based views, but I also think we should carefully think through each such use case and think about alternatives: custom directive, view composition, an event system, etc.

If we want class based views I think we could implement it in such a way that we can determine that a class is in use during registration, so we can avoid doing the 'isfunction' check during runtime.
