### ISSUE TITLE
request.path

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#281]
I'd be useful to have a request.path() which, given a path in the context of this application, returns the object created by the path function (or None). So:

```
request.path('documents/3')
```

Perhaps even more useful would be a request.path() that could be given the path pattern and the arguments separately, as then there's no need to serialize them again:

```
request.path('documents/{id}', id=3)
```

This should of course take an 'app' argument like 'link' and 'view'.

**Comment by webmaven** [comment]
:+1:

**Comment by faassen** [comment]
I implemented the full resolution of the path as with ``request.path('documents/3')`` but does not implement the second one. The signatures are not compatible I think, so we need another method to implement that.

One reason to introduce these that I had was the ability to override a path directive with another one, and reusing the original implementation. But this wouldn't work, as it'd result in infinite recursion instead.

**Comment by faassen** [comment]
Note that the implementation is now `request.resolve_path` due to naming conflicts with WebOb's `request.path`

**Comment by faassen** [comment]
Since this is already implemented, closing this issue.
