### ISSUE TITLE
event system?

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#284]
Does Morepath need an event system? I've considered it more useful in a ZODB/traversal context, but haven't thought it through a lot. Study Pyramid's event system.

**Comment by andrss** [comment]
It definitely does. We are considering Morepath as a foundation for ERP/e-commerce framework and event system in this case is a must.

**Comment by faassen** [comment]
Cool to hear that. Could you go into a bit more detail concerning your requirements concerning an event system? Are you looking for something like Pyramid's,  or something else? Which event types are most interesting to you?

Note that Morepath may not need an actual notion of an event -- just implementing a few hooks that call the appropriate generic functions may be enough. The developer can then implement those generic functions in their application if they wish to do so. Subscribing to the right events would be done by using Reg's predicate system (which may need some streamlining to let you express some things more easily). 

The one thing you can't do with this is define multiple subscribers for the same event. I'd prefer to solve this in a general way in Reg if possible.

**Comment by andrss** [comment]
We need to create custom event types and ability to subscribe to those events from any module of our framework. It is important for us to be able to define multiple subscribers for the same event. Pyramid-like event system will be fine with one difference though: in case of multiple subscribers to the same event type we need a way to define the particular order of subscribers to be called relative to each other. We understand it could be realized to some extent by using third party libraries, but it would be real nice to have such powerful and flexible event system as part of Morepath.

**Comment by faassen** [comment]
So it is more about custom events with multiple subscribers than Morepath itself sending some specific events.

May I ask why ordering subscribers is important? I could introduce a topical sort feature like we have for tweens and predicates, where you can refer to the subscriber you want to be fired after or before in the decorator. On the other hand, if there is a dependency between subscribers, you could simply express that by calling multiple functions in order in a single subscriber, so I'm trying to imagine the use case. I guess one subscriber can be more specific than an other one, so they don't *always* all fire, but when they do, you want a certain order, but I'd like to hear more.

I created an issue for the Reg project as I think this facility really belongs there:

https://github.com/morepath/reg/issues/21

**Comment by andrss** [comment]
Since the framework we are developing will have highly modular architecture in which some modules will depend on other modules it is important to provide the developer of the dependent module with ability to influence the behavior of the module the dependent module depends on. There are different scenarios possible when it is necessary to replace event handler in base module by event handler in dependent module or provide the ability for event handler in dependent module to fire before or after the event handler in base module does.

**Comment by faassen** [comment]
Replacing event handlers is an interesting issue you bring up, and which I need to consider

In Morepath's configuration system all directives have an identifier, based on the arguments to it -- the path for the path directive, the model and name and request method (etc) for the view directive, etc. This identifier is used to detect conflicts in configuration (saying the same thing twice is an error), and also importantly to implement a general system for overrides in application subclasses.

In an event system, a subscriber does not have a clear identifier, as the whole point is that you can have more than one subscriber for a set of arguments being subscribed to: multiple handlers for the add event of a model, say. A way around this is to make each identifier completely unique so they never conflict -- but this also means an override is never possible.

Even with such a system you *could* create overridable event handlers by having the subscriber call a generic function, which you can then subsequently override. But that requires anticipation, and so is not ideal.

One way to make overrides possible is to make the decorated function of the original subscriber *be* the identifier. To override you can then refer to that function explicitly in the overriding subscriber's arguments, like this hypothetical code:

```
@App.subscriber(event=BlahEvent)
def foo_handler(event):
    ...

@SubApp.subscriber(event=BlahEvent, override=foo_handler)
def bar_handler(event):
   ...

Unfortunately Morepath's configuration today won't allow that. And it's a bit ugly anyway.

The whole notion of "events" as an explicit class is something I'd like to avoid, as generic functions are *so* close anyway - it'd prefer to expand on that story. But even if I somehow expand it so that a single generic function call can cause multiple functions to be called in the end,  I still don't know what an override would look like.

**Comment by faassen** [comment]
Closing this for now. If someone wants to help flesh this out feel free to reopen it.
