### ISSUE TITLE
The request.path method breaks more.transaction

### ISSUE THREAD

**Issue by href** [morepath/morepath#292]
The latest commit introduces a `request.path` method. See https://github.com/morepath/morepath/commit/8146d1b023fbed49d0951a9dafe73cda7d2fed01.

This change breaks `more.transaction`. The tests still pass because a dummy request is used, but when using `more.transaction` for real the transaction cannot complete, [because of this line](https://github.com/morepath/more.transaction/blob/646f8a752e5f95c659a902a564f18260b112df32/more/transaction/main.py#L64)

I would've added this as a `more.transaction` issue, but I think other places might be affected as well and I was wondering:

Wouldn't it make more sense to introduce this method under a different name? Currently this method overrides `webob.request.BaseRequest.path`, which is a property.

I would imagine that being compatible with webob's request comes with certain benefits down the road.

**Comment by faassen** [comment]
Yes, I made a mistake and shouldn't have overridden webob's request! We need to change it in Morepath to something else. I used 'path' in analogy with 'view', but clearly we need something more involved. I propose 'resolve_path'. Feel free to come up with a pull request that fixes this!

**Comment by href** [comment]
`resolve_path` sounds good to me, you'll get a PR.

**Comment by href** [comment]
I can confirm that this works now.
