### ISSUE TITLE
Should conflicts between paths and views be reported?

### ISSUE THREAD

**Issue by href** [morepath/morepath#295]
The following code silently introduces a conflict:
```
config = morepath.setup()

class App(morepath.App):
    testing_config = config

@App.path(path='')
class Root(object):
    pass

@App.view(model=Root, name='info')
def public_view(self, request):
    return 'public root'

@App.path(path='info')
class Info(object):
    pass

config.commit()

c = Client(App())
c.get('/info')
```
This will return a 404 Not Found. I would have expected for this to result in a conflict error. Is there a reason for this?

**Comment by faassen** [comment]
There's a way to explicitly ask for the view: /+info

http://morepath.readthedocs.org/en/latest/views.html#ambiguity-between-path-and-view

**Comment by href** [comment]
Oh I shouldn't have missed that :flushed: 
Thanks!
