### ISSUE TITLE
WebKitFormBoundary?

### ISSUE THREAD

**Issue by davclark** [morepath/morepath#297]
I'm using bootstrap3 to send a `multipart/form-data` encoded POST to morepath. The POST dict ends up empty, and request.body is simply (e.g.):

```
------WebKitFormBoundarycBP7lGPmCRmryUSw--
```

Does support for this need to be added?

**Comment by davclark** [comment]
Hmm... actually, there appears to be a more fundamental problem with my form... please ignore for now.

**Comment by faassen** [comment]
Ok! Hope you got it fixed!
