### ISSUE TITLE
Application settings loaded after templates

### ISSUE THREAD

**Issue by href** [morepath/morepath#298]
I'm trying to implement my own chameleon template loader that offers localization. Mostly due to the fact that it's just not that hard - so I feel like I can skip more.chameleon ;)

I'm doing something like this:

``` python
import chameleon
import gettext

from onegov.core import Framework
from translationstring import ChameleonTranslate
from translationstring import Translator

@Framework.template_loader(extension='.pt')
def get_template_loader(template_directories, settings):
    translation = gettext.translation(
        settings.i18n.domain,
        settings.i18n.localedir,
        settings.i18n.languages
    )

    translator = Translator(translation)
    translate = ChameleonTranslate(translator)

    return chameleon.PageTemplateLoader(
        template_directories,
        default_extension='.pt',
        prepend_relative_search_path=False,
        auto_reload=False,
        translate=translate
    )
```

This is pretty much a copy of more.chameleon. However, it is supposed to load the following settings from applications inheriting from Framework:

``` python
@TownApp.setting(section='i18n', name='domain')
def get_i18n_domain():
    return 'onegov.town'

@TownApp.setting(section='i18n', name='languages')
def get_i18n_languages():
    return ['en', 'de']

@TownApp.setting(section='i18n', name='localedir')
def get_i18n_localedir():
    return utils.module_path('onegov.town', 'locales')
```

The problem is, that these settings are not available when `get_template_loader` is called. They become available only later. They are available if I move them to the Framework class, but that's no use to me since I want those settings to be specific to each application.

I was expecting that these settings would be loaded first in any case. Is this a bug?

**Comment by faassen** [comment]
Could indeed be a bug! I just checked and settings ought to be available due to the depends relationship on the directive.

I do not have time to chase this one down in the next days. You can try yourself, but a test failure with this isolated would also help a lot and is a good place to start anyway.

**Comment by href** [comment]
Okay thanks, I try to prove this bug in a test.
I just wanted to be sure that this is not something that's obviously impossible.

**Comment by href** [comment]
I wrote a test which didn't fail, I tested the issue again like before and I don't see it happening anymore. I'm pretty sure I did something wrong the first time around. False alarm!
