### ISSUE TITLE
Absolute template directories should work without Morepath having to know the module path

### ISSUE THREAD

**Issue by href** [morepath/morepath#299]
The documentation states that it should be possible to either return a relative or an absolute path for the template_directory directive.

The code indicates however that this doesn't work: https://github.com/morepath/morepath/blob/979ac10c98c129f812a65bf6b24c01105bf28547/morepath/directive.py#L402

I also couldn't find a test that checks that. Am I missing something?

**Comment by faassen** [comment]
Perhaps there's no test, but it ought to work. Try this in Python:

```
  os.path.join('/original', '/new')
```

**Comment by href** [comment]
That's true. I looked at it again and my issue is ill-defined. :sweat: 

I do have the problem that I can't return an absolute path *in tests*, because they happen in a pytest folder without __init__.py. Which results in `self.attach_info` being None.

See https://github.com/OneGov/onegov.core/blob/a609/onegov/core/tests/test_templates.py#L53

That assertion threw me off here. I think it's not necessary if the path given is already absolute, no?

**Comment by href** [comment]
I'm back and I would like to fix this, but I wanted to get your feedback first :)

https://github.com/morepath/morepath/blob/979ac10c98c129f812a65bf6b24c01105bf28547/morepath/directive.py#L402 asserts that attach_info is not None:

```python
    def perform(self, registry, obj):
        directory = obj()
        assert self.attach_info is not None
        directory = os.path.join(os.path.dirname(
            self.attach_info.module.__file__), directory)
        registry.register_template_directory_info(
            obj, directory, self.before, self.after, self.app)
```
This seems unnecessary, *if* the directory is already an absolute path, since the first parameter of os.path.join is simply ignored in this case.

So I would rewrite this as follows:

```python
    def perform(self, registry, obj):
        directory = obj()
        if not os.path.isabs(directory):
            assert self.attach_info is not None
            directory = os.path.join(os.path.dirname(
                self.attach_info.module.__file__), directory)
        registry.register_template_directory_info(
            obj, directory, self.before, self.after, self.app)
```

What do you think?

**Comment by faassen** [comment]
Change sounds good to me! As long as the tests pass feel free to check it into master.

Though a note about an earlier comment you made: you said attach_info is `None` as they happen in a pytest folder without `__init__.py`. But in tests it's usually `None` as no Venusian scanning takes place in the first place (only tests that explicitly scan have it).

P.S. Great, welcome back! I hope you had a good trip!

**Comment by faassen** [comment]
Put a comment about what you did and why in `CHANGES.txt` too, please. You can refer to this issue in it. Not sure whether an (API) doc update is needed to describe this use case.

**Comment by href** [comment]
Okay, thanks. I'll do that.

**Comment by faassen** [comment]
Exciting to see someone besides me put things into master! :+1:

**Comment by href** [comment]
There you go, the API didn't need updating as it already mentions that paths are relative to the module and there's no change in that behavior.

**Comment by faassen** [comment]
Hm, do the docs also say you can put in an absolute path?

**Comment by href** [comment]
They do: https://github.com/morepath/morepath/blob/979ac10c98c129f812a65bf6b24c01105bf28547/morepath/directive.py#L365

**Comment by faassen** [comment]
Oh, I must've done that already back then. :) Thanks for double checking!

**Comment by href** [comment]
Welcome ;)
