### ISSUE TITLE
HTML template language support

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#3]
Allow a template= argument to the @app.html decorator. If the function then returns a dictionary (or non-string, perhaps, any other object?) it will combine it with the given template. The template language's extension will indicate how this works. We need
a plugin system so that new template languages can be integrated.

**Comment by faassen** [comment]
See https://gist.github.com/faassen/ca56fb32f0ebc9d6e0da for a sketch of how this can work.

Thanks to all the feedback, also from @kagesenshi who wrote this:

https://github.com/koslab/more.chameleon

Everybody seems to be going for the 'render' function infrastructure to do this, which inspired me to generalize what a template really is.

**Comment by faassen** [comment]
I've also created more.chameleon here: 

https://github.com/morepath/more.chameleon

It uses the new integration stuff. I still intend to test a few more features (loading other templates, auto reload feature), but it seems to work.

**Comment by href** [comment]
This looks really nice, I like the new directive. This would make it trivially easy to implement a custom renderer!

**Comment by faassen** [comment]
Thanks!

What do you mean by a custom renderer, exactly?

**Comment by faassen** [comment]
Closing this one as we've got templating for a while now.
