### ISSUE TITLE
put externally created extensions in morepath project

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#300]
more.jwtauth, @href's stuff?

**Comment by href** [comment]
I'm all for it :+1:

**Comment by faassen** [comment]
I've created an Extensions group and both you and @henri-hulski are invited into it. Please transfer the more.* projects you want to be in the main organization repo over into it, and remind me on this issue to add it to the Extensions group so you both have access.

**Comment by href** [comment]
I added [more.webassets](https://github.com/morepath/more.webassets) and [more.itsdangerous](https://github.com/morepath/more.itsdangerous) to Morepath and the Extensions group.

**Comment by faassen** [comment]
Great, thank you!

**Comment by henri-hulski** [comment]
I transferred [more.jwtauth](https://github.com/morepath/more.jwtauth) to the Morepath Extensions group.

**Comment by faassen** [comment]
Thanks! I'll close this issue, as stuff has been transferred. If we have new things to transfer we can create new issues.
