### ISSUE TITLE
Can't get authentication mechanisms to work at all

### ISSUE THREAD

**Issue by davclark** [morepath/morepath#305]
I feel I've tried to follow the docs pretty carefully, [using both more.itsdangerous](https://github.com/davclark/morepath-auth/blob/minimal-nonworking/morepath_auth/main.py) and [the built-in Basic Auth](https://github.com/davclark/morepath-auth/blob/permissions/morepath_auth/main.py).

Basically, using itsdangerous, while the `remember` function will get called via `@request.after`, and I can see a cookie in the response, I never obtain any identity apart from `NO_IDENTITY`.

Once I implement a security policy (even if it's a function that returns True), I'm unable to see pages with permission. I thought maybe something was perhaps confused by the itsdangerous code, but the problem persists even after I switched to Basic Auth. I also tried changing to a 401 code, but my browsers don't ask me for basic auth either... I'm guessing this is disabled on non-SSL connections?

In any case, I have vastly exceeded my time budget on figuring this out - I'm trying to implement some stuff to help with a clinical trial, and very much like the design of Morepath. But, if I can't have authentication, I can't use it. So, I hope to get some pointers!

I don't expect you to debug my code - but the intent is for you to have a minimal non-working example. I'd be happy for a pointer to working code.

**Comment by davclark** [comment]
OK - I tried one last thing, which was to add a permission rule for identity=None (it wasn't clear that NO_IDENTITY would be excluded). So, both my links from above are now using itsdangerous. My guess is that I need to ask the browser for a cookie. I just don't know how to do that.

**Comment by davclark** [comment]
Oh - and I should cc @href, I recon. To be extra clear - I did some more digging, and I think the cookies should get sent... there is no domain specified, and so the cookies should be sent back "dynamically" to the site that set them (here, localhost).

**Comment by faassen** [comment]
The two examples you pointed to both seem to link to a itsdangerous based auth as opposed to basic auth.

For basic auth, did you include a view like this one to turn Forbidden into Unauthorized? Hm, you say you do. I am not aware that browsers refuse to do basic auth for non-HTTPS connections.

```
    @app.view(model=HTTPForbidden)
    def make_unauthorized(self, request):
        @request.after
        def set_status_code(response):
            response.status_code = 401
        return "Unauthorized"
```

It's possible that this is related to issue #228, though it looks like it isn't as you do see the cookie on the response.

I see that your Permission is not a subclass of `object`. If you're in Python 2, you do need to subclass `object` here I thin.

PS: I know that @href may not be on the internet much during this period, so his response may be slow. Maybe @henri-hulski can jump in as he also implemented auth.

**Comment by henri-hulski** [comment]
At the moment I have no time to look at this, but maybe you take a look at morepath/tests/test_security.py.  There is a working example for basic auth. 
I have implemented the JWT auth which is token driven, so I don't know about cookies.

**Comment by faassen** [comment]
Thanks @henri-hulski!

It's not immediately obvious to me what's wrong with your code, Dav -- if you still can't figure it out I'll try to take a look at it tomorrow.

**Comment by seyhbold** [comment]
Hi All,

the more.itsdangerous.IdentityPolicy sets the `secure` config to `True`. So while working on a development server without `https` it won't get stored.
If you set the setting to `False` the `minimal-nonworking` example of @davclark works.

Cheers
Ludwig

**Comment by davclark** [comment]
Thanks Ludwig!

To answer @faassen - I guess I wasn't clear enough about changing both versions to using itsdangerous (as I solved one of the two problems). Thanks to @seyhbold for solving the other.

**Comment by faassen** [comment]
Thanks @seyhbold!

**Comment by href** [comment]
Thanks everyone for having a look at this in my absence. This will be improved in the future, see https://github.com/morepath/more.itsdangerous/issues/1

**Comment by faassen** [comment]
I like how this issue involved 5 people; Morepath's definitely growing! :)
