### ISSUE TITLE
How do I respect CORS requests?

### ISSUE THREAD

**Issue by seyhbold** [morepath/morepath#307]
Hi,

I just try to access a morepath server from another domain.
Is there any sample on how I would deal with CORS requests?

Thanks
Ludwig

**Comment by seyhbold** [comment]
Ok, found myself.

```python
@App.tween_factory()
def make_tween(app, handler):
    def add_cors(request):
        response = handler(request)
        response.headers['Access-Control-Allow-Origin'] = 'http://localhost:8001'
        return response
    return add_cors
```

**Comment by faassen** [comment]
Oh, good that you found it! I was going to have to read about CORS myself first. :)

The tween seems like a decent solution. Potentially there's room for some extension that implements a directive to set this up, but this is already pretty small in the amount of code needed.

**Comment by seyhbold** [comment]
Is there any documentation on how to build own directives, especially in this case on how to combine it with the `@App.json` directive?

**Comment by faassen** [comment]
Ah, unfortunately this is still the one aspect of Morepath's documentation that's missing. You can find examples of how directives are built by looking at directive.py in Morepath or, to see smaller examples, study some of the `more.*` extensions out there.

As to combining with `@App.json`, directives are stand-alone and don't combine. Instead, you could consider implementing a new view directive subclassing the JsonDirective. Alternatively for this CORS stuff you could also implement it by putting in a custom ``render`` function that sets the information on the response.

**Comment by faassen** [comment]
@seyhbold in case you haven't seen it, http://dectate.readthedocs.org now documents how to build directives. ``directive.py`` inside Morepath also provides a diversity of examples. Closing the issue for now.
