### ISSUE TITLE
Choose view based on path prefix

### ISSUE THREAD

**Issue by seyhbold** [morepath/morepath#308]
Hi,

I have one issue with paths I can't figure out.

I have a set of documents published under a certain path e.g. `docs` and a single doc on `docs/{id}`.
Now I would like to have a separate path to display the docs as graph nodes which look very different as they contain layout information, color etc. e.g. `nodes` and `node/{id}` would this be possible?

Thanks Ludwig

**Comment by faassen** [comment]
Morepath does not let you expose the same class under two paths in the same application. There are some options you have:

* create a new class (a subclass or probably better, a wrapper that adapts the original class).

* do this in two separate applications for docs and nodes and mount them into a core application. You can create different paths for the same class that way.

By the way, I think a question like this is better for the mailing list as opposed to the issue tracker.

**Comment by seyhbold** [comment]
Thanks for the answers. You're right I didn't notice the mailinglist
