### ISSUE TITLE
Buildout conflict between flake8 and prospector

### ISSUE THREAD

**Issue by henri-hulski** [morepath/morepath#310]
prospector 0.10 has the dependency pep8 >= 1.6.0
flake8 2.4.0 adds the dependency pep8 < 1.6
See [Changes](http://flake8.readthedocs.org/en/latest/changes.html).
Related to [GitLab#35](https://gitlab.com/pycqa/flake8/issues/35).

So maybe we should depend on flake8 2.3.0.

**Comment by faassen** [comment]
I think it's better to just rip out prospector. I use flake8 a lot but prospector I rarely use as it gives a ton of spurious output, partially due to pylint not really understanding Reg. I use mccabe standalone anyway. Can you do it?

**Comment by henri-hulski** [comment]
Sure

**Comment by henri-hulski** [comment]
Done.

**Comment by faassen** [comment]
Since this was merged I can close this issue, thanks!
