### ISSUE TITLE
How to serve images with morepath?

### ISSUE THREAD

**Issue by binbrain** [morepath/morepath#314]
I realize that morepath defers the serving of static resources such as css and js to libs such as bowerstatic and fanstatic. However, as far as I can tell, none of the options listed in the documentation provide an avenue for serving images.  In order to tell the full "web framework" story, I feel like the morepath documentation should at least mention some working solution for this, even its not built into the framework itself.

**Comment by href** [comment]
That is true. I've been meaning to add my example to the docs:
https://gist.github.com/href/a4edb486bfac45521342

So much to do, so little time :)

**Comment by faassen** [comment]
Hey,

It would be useful to get at the core of this approach in the docs. Denis'
example is one way to organize things but there are many options.

Basically from any Morepath view you can return a webob Response object.
You can fill this with the binary body you like and set its content type.

This webob doc describes what you can do:

http://webob.readthedocs.org/en/latest/file-example.html

And refers to StaticFile which does it all for you.

I think at the very least we should add a section to the docs that points
here. James, want to work on a pull request for this?

Regards,

Martijn
