### ISSUE TITLE
Test Morepath on Travis

### ISSUE THREAD

**Issue by href** [morepath/morepath#325]
I just noticed that there is no CI server for Morepath. Since Travis does this sort of thing for free for open-source projects: Any reasons not add it there?

**Comment by faassen** [comment]
No reasons, just lack of time/knowledge on my part. Go ahead and add it. :)

**Comment by href** [comment]
I feel much better now ;)
https://travis-ci.org/morepath/morepath

**Comment by faassen** [comment]
Thanks! Should we include a travis badge or something in the github?

**Comment by href** [comment]
Yeah, why not. While I'm at it I can also add Morepath to coveralls to get a test coverage batch.

**Comment by href** [comment]
I added the batch for Travis. Coveralls looks harder than I thought, since py.test -cov doesn't seem to work with Morepath's test layout. I don't have much time to go into this, so I leave it as it is for now.

**Comment by faassen** [comment]
I do have coverage testing working with py.test:

https://morepath.readthedocs.org/en/latest/developing.html#running-the-tests

Can't we use this command with coveralls?

**Comment by href** [comment]
I don't know what I was thinking - It's working now.
I also added a badge for the coverage.

**Comment by faassen** [comment]
Pretty cool! We are all futuristic and stuff with our badges. :)
