### ISSUE TITLE
Document morepaths config scanning clearly and early

### ISSUE THREAD

**Issue by href** [morepath/morepath#327]
Currently, it is not obvious to newcomers how and when to use what kind of morepath config scans to run. The API is the only place where this is really documented.

As we've seen in https://github.com/morepath/morepath/issues/323 we can improve on this situation.

It might even warrant its own section that includes #319 and the upcoming entry point changes.

**Comment by faassen** [comment]
Good idea! 

We should create a new page in the documentation that document it, and link to it from the various other places where we mention it, including the API docs.

**Comment by href** [comment]
This has been implemented in #319
