### ISSUE TITLE
Autosetup should include caller package

### ISSUE THREAD

**Issue by href** [morepath/morepath#331]
Currently, this is our quickstart story:
```python
  import morepath

  class App(morepath.App):
      pass

  @App.path(path='')
  class Root(object):
      pass

  @App.view(model=Root)
  def hello_world(self, request):
      return "Hello world!"

  if __name__ == '__main__':
      config = morepath.setup()
      config.scan()
      config.commit()
      morepath.run(App())
```

Working on the upcoming configuration docs I realized that we could make this shorter if we made autosetup scan the caller package as well (just like `config.scan` does). The change is rather trivial and the tests seem to pass with only a minor change (morepath ends up being scanned twice - the tests are not properly independent yet).

Autosetup would basically become this:
```python
def autosetup(ignore=None, include_caller_package=True):
    c = autoconfig(ignore)
    if include_caller_package:
        c.scan()
    c.commit()
```

And the quickstart could be made into this:
```python
  import morepath

  class App(morepath.App):
      pass

  @App.path(path='')
  class Root(object):
      pass

  @App.view(model=Root)
  def hello_world(self, request):
      return "Hello world!"

  if __name__ == '__main__':
      morepath.autosetup()
      morepath.run(App())
```

What do you think?

**Comment by faassen** [comment]
I think this would be a good idea, but what does happen when things get scanned twice? Wouldn't this cause any Python project to be scanned twice too?

Anyway, I'm +1 for this is we can get the code reasonably elegant.

**Comment by href** [comment]
> But what does happen when things get scanned twice? Wouldn't this cause any Python project to be scanned twice too?

I'm not quite sure what you mean, why would it get scanned twice? If you are referring to my comment about the tests: They run through if run separately, but together they fail. So I figured there's some test separation issue there.

**Comment by faassen** [comment]
A Python project gets scanned because it depends on Morepath. And because
the startup package runs autosetup. Wouldn't this cause a double scan?

**Comment by href** [comment]
I see. Yes I think you might be able to provoke a double scan.Maybe the `autosetup` could be smarter and only scan the caller package if it's not a morepath_package. Or if it wasn't already scanned, though we'd have to keep track of the scanned packages in this case.

**Comment by faassen** [comment]
Yes, I do think we need something smarter. I don't know yet whether this explains the test isolation issues you see, but it could be.

**Comment by href** [comment]
You might be right, the test issue could be because the code is not smart enough. Once I'll find time I'll take a stab at this again.

**Comment by faassen** [comment]
Scanning changed a lot after Dectate. The quickstart example is simpler now. Still, autosetup *could* still do a scan of the package it finds itself in too -- since imports won't be happen again we don't run the risk of double imports, *except* for the module that defines ``if __name__ == '__main__'`` as documented by dectate now. On the other hand, a plain import in quickstart will always work and no confusion about scanning will happen. So actually I'm a bit concerned that if people expand the quickstart example they run into this pattern...

What do you think, @href?

**Comment by href** [comment]
The new way seems sufficiently short for my taste actually. It's pretty close to what I had in mind.
