### ISSUE TITLE
update REST document with new info about Morepath's HTTP status handling

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#332]
The document here:

https://morepath.readthedocs.org/en/latest/rest.html

doesn't refer to more modern approaches in Morepath that handle HTTP status codes. It should be updated.

**Comment by webmaven** [comment]
:+1: 

Can you provide an outline that would serve as a guide for the update?

**Comment by faassen** [comment]
I've updated it quite a bit to discuss 422, and body_model.
