### ISSUE TITLE
cov during pypy tox tests

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#333]
I just ran the tox tests and I got this:

ERROR: InvocationError: '/home/faassen/projects/morepath/.tox/pypy/bin/py.test morepath --cov morepath'

I wonder what triggered this. Wiping my .tox doesn't fix it. I think you added the coverage reporting, @href?

**Comment by href** [comment]
Works for me. Maybe it helps if you delete/rebuild your buildout directory (that is to say the morepath development environment)? Because that's what happens on Travis, where this directory is rebuilt every time.

**Comment by faassen** [comment]
I'll try that. I tried removing the `.tox` dir but that wasn't good enough. I also had it fail on a `flake8` command for some reason.

**Comment by faassen** [comment]
I might have gotten this error due to a test failure, not sure. Anyway, closing it for now.
