### ISSUE TITLE
underscore in project names

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#334]
I tried to create a project morepath_batching. Unfortunately when I try to run it through an entry point, I get this error (not in Morepath 0.10):

```
morepath.error.AutoImportError: Morepath wanted to import 'morepath-batching' during auto-configuration, but
no such module could be imported.

Make sure your module name matches the setup.py name, or use
manual configuration:

    import yourmodule
    import morepath

    config = morepath.setup()
    config.scan(yourmodule)
    config.commit()

For more information have a look at the 'morepath.autoconfig' docs.
```

@href, this seems to be due to some magic setuptools behavior that turns underscores into `-` sometimes. Any ideas?

**Comment by faassen** [comment]
I think our auto-import code should try to convert any - in package names into a _... I'll give that a try.

**Comment by faassen** [comment]
Yet, doing a  `distribution.project_name.replace('-', '_')` in `get_module_name` does the trick.

**Comment by href** [comment]
Yes this seems to be setuptools magic. I think we can add your fix to the code, as modules with a dash in them won't be importable anyway.

For 0.11 you could work around the problem by defining an entry_point for projects with underscores in them.

**Comment by faassen** [comment]
I just went and added a test that demonstrates the problem and fixed it. Releasing a 0.11.1 to be done with it. :)

**Comment by href** [comment]
Cool, thanks! :)
