### ISSUE TITLE
@request.after ignored if redirect returned

### ISSUE THREAD

**Issue by binbrain** [morepath/morepath#338]
In the docs on security and in this blog http://blog.startifact.com/posts/morepath-security.html it explains using @request.after to remember identity. However, the response method at view.py:30 ignores the _after list if HTTPFound is in the content which would be the case if morepath.redirect(loc) is returned. This means a view method that tries redirect on successful user_has_password will not have its @request.after methods called.

**Comment by binbrain** [comment]
I see that this behavior is explained in the documentation on request.after. I might be misunderstanding, but since a redirect seems like a very common action to take after verifying identity, I might suggest that the security docs elaborate more on whether or not to use request.after.

**Comment by faassen** [comment]
cc-ing @href as he ran into this before too.

**Comment by href** [comment]
I'm not sure I can add much information to this. Using `request.after` with a redirect is not possible. This is what I ended up doing instead:

https://github.com/morepath/morepath/issues/177#issuecomment-80406740

**Comment by href** [comment]
This is exactly what I do in one view:

1. Check the username/password
2. Redirect to some url if the username/password match.
3. Return content with an error if there's no match

You can see this happening here:
https://github.com/OneGov/onegov.town/blob/master/onegov/town/views/login.py#L54

**Comment by binbrain** [comment]
Thanks @href that's looks like its exactly what I'm looking for.

**Comment by href** [comment]
Welcome, feel free to open more issues if you have more questions/notes.
