### ISSUE TITLE
Enable generation of URL template links for paths with variables

### ISSUE THREAD

**Issue by guido-weber** [morepath/morepath#340]
If we have a path declaration like this:

@App.path(path='some/path/{variable}', model=...)

there are situations where we want to hand of the path template to some other system (e.g. the
JS code in a single page app may need to generate different links from some internal data and
the path template). Currently, this is not possible with the request.link() call, as that call requires
a concrete model instance to work with.

**Comment by href** [comment]
You might be able to use some abstract base class registered for a path instead to work around the problem. This base class would hold all the properties needed to construct the path. Your actual model would then inherit from said base class.

That being said, maybe there would be some value in an approach where we pass the model class together with some arguments to `request.link`. I'm just concerned that this might lead us closer to the traditional approach of named paths. Having access to the path by class is not fundamentally different from having access to the path by some name. Morepath's approach of paths by model is what made me care for it in the first place.

Just my two cents, I'm sure @faassen has a much better view to offer.

**Comment by guido-weber** [comment]
@href: I think you misunderstood me. What I want to do is, get the path **including the {variable} part** to hand it to some other system. That system would then be able to generate URLs without interaction with morepath. The information is obviously already in morepath, it is just ;-) a question of getting it out again.

**Comment by href** [comment]
I see. In this case I'm as interested in the answer as you are :)

**Comment by faassen** [comment]
Closing this one, merging it into #359
