### ISSUE TITLE
readthedocs sidebar has history of morepath fall off

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#344]
At least on my screen I cannot see 'history' as an entry. It seems to be covered by the 'read the docs' widget.

**Comment by href** [comment]
I have the same problem on my notebook. If we can get some custom css into the documentation we can work around this issue by adding some empty space after the last sidebar entry.

**Comment by faassen** [comment]
Not sure how to make that css happen there. We should consider showing less entries too to be less intimidating. But that requires new level in docs.

**Comment by href** [comment]
I did it before, but it's not very straight forward. So I'm +1 on docs organisation.

**Comment by faassen** [comment]
Maybe you can go through the entries and categorize them. I also want to add a tutorials entry and convert one or two of my blog posts and write up more.

**Comment by href** [comment]
My first impulse would be to put them into these top-level categories:

* First Steps (Index, Quickstart, Community, Installation, Superpowers)
* Deep Dive (The bulk of it) <- can we split this up more?
* Morepath API
* Development (Developing, Changes, History)

**Comment by faassen** [comment]
I think changes should go in a more prominent place as it is for people who upgrade.

**Comment by href** [comment]
Then maybe like this?

* First Steps (Index, Quickstart, Community, Installation, Superpowers)
* Deep Dive (The bulk of it)
* Morepath API
* Changes
* Developing
* History

We can also point to the changes from the index page.

**Comment by taschini** [comment]
Anything left to do here?

**Comment by faassen** [comment]
No, this is done, thanks very much, this improved the docs quite a bit I think. Closing the issue.
