### ISSUE TITLE
webob links are broken in docs

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#348]
I'm talking about stuff like the reference in the `Request` class docstring, which points to webob.

Probably need to adjust the sphinx config to make it point the right way for the `meth:webob` stuff.

**Comment by href** [comment]
The latest build of the docs does not have this problem anymore. So latest now works and I'm rebuilding stable.

**Comment by href** [comment]
I think this can be closed, I can't reproduce this problem in the docs anymore.

**Comment by faassen** [comment]
Thanks!
