### ISSUE TITLE
somehow detect functions in modules that have the same name

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#350]
A common pitfall of beginners is to copy a view and then have the same function name as one that is already in the module. The last one wins, and that's just Python. But it would be nice if the decorator machinery could somehow detect this as an error, if at all implementable.

**Comment by href** [comment]
Flake8 detects this, so maybe there's something to be used there?

**Comment by faassen** [comment]
Yeah, and we could simply recommend flake8 to be used by people. I don't think we can use flake8's implementation though -- it is a big dependency and it parses Python code, doesn't it? Instead the decorator machinery might be able to detect this by inspecting function names. I wish Venusian had a different way to detect registrations in modules; I believe it currently just scans through everything in the module instead of having the decorators store the base configuration in a separate per-module registry.

**Comment by faassen** [comment]
Since flake8 detects this it's not really a Morepath issue. Also with Morepath 0.13 this problem has decreased as multiple registrations will work where they didn't do before.
