### ISSUE TITLE
cookie cutter tool to generate Morepath projects

### ISSUE THREAD

**Issue by gnimmelf** [morepath/morepath#352]
Hi all,

Just starting out with morepath, and being more or less a setuptools/wsgi-newbie, I have no idea how to actually even start the application from the command-line using python setup.py [...]. There is so much heavy documentation for both setuptools and wsgi, that google hasn't shown me the way yet (I'm lazy!).

Maybe it would be a good idea just to include a section in the documentation on various ways to run an entry_point. The only one working for me now is `setup.py install`, then cmd-line the entry-point-name (which tells you how a newbie I am), but I cannot get that to work with the `wekzeug` reloader...

(From #345, related to #347?)

**Comment by href** [comment]
Can you post your code somewhere online so I can have a look at it? The werkzeug reloader issue is probably unrelated.

About the entry-points. As far as I know there's only one way to use them. Install them using `python setup.py install` and then calling the command by name.

Alternatively you can simply run the script the command is pointing to, as long as you have a section like this in the same file:

```python
if __name__ == '__main__':
    main()
````

You could call that script like this: `python myproject/run.py`.

**Comment by gnimmelf** [comment]
The code lives here,
https://github.com/gnimmelf/morepath-blog

As for the entry-points, I assume you are right. I guess my confusion was that werkzeug `use_reloader` did not work calling the setup-generated command, so I kept looking for a way to run the entry-points directly (npm-influenced, I guess). And with the amount of documentation available, I assumed I just couldn't find it, not that it didn't work that way!

**Comment by faassen** [comment]
I think this discussion is a good argument for having an automated project creation tool for Morepath. setup tool for Morepath. We could just steal whatever Pyramid does if possible and use that.

**Comment by href** [comment]
> We could just steal whatever Pyramid does if possible and use that.

I don't know how Pyramid does it, but I'm firmly in camp [cookie cutter](https://github.com/audreyr/cookiecutter), so I would personally just create a cookie cutter template. I have some experience with that.

**Comment by faassen** [comment]
Are you still interested in doing a cookie cutter template?

**Comment by href** [comment]
Sure, I'll create one when I find the time.

**Comment by faassen** [comment]
See also #194

**Comment by href** [comment]
I created one and I'd welcome some feedback:

https://github.com/morepath/morepath-cookiecutter

**Comment by faassen** [comment]
Awesome! I am creating a bunch of issues but they're minor issues and it's because I'm so enthusiastic!

**Comment by faassen** [comment]
We should get this written up in the official documentation as soon as possible. Should we leave the text in README or should we include this in the Morepath docs instead?

**Comment by href** [comment]
Cool :)

I think we should keep the README with the template. That's pretty common around cookie-cutter templates, which often get forked and customised.

**Comment by faassen** [comment]
Okay, then we need a strategy to include this in the docs. I think we need a reference in a sidebar in quickstart. I think we need to rearrange install to make this approach the prominent one, and split off the alternative methods into a separate document we link to ("manual_install" or something like that). We also need to make it very clear in organizing your project that this template is the way to go.

**Comment by faassen** [comment]
We can refer to the cookiecutter template with a link, with an introductory paragraph; we don't need to replicate the instructions in the Morepath docs. That might mean install.txt becomes super small, so perhaps splitting off a separate doc isn't the right way to go. Instead we should start out the cookiecutter approach and make it prominent somehow, and then go on to the manual methods.

**Comment by href** [comment]
> Okay, then we need a strategy to include this in the docs. I think we need a reference in a sidebar in quickstart.

I'm not sure it belongs to quickstart. I expect that to be the explanation of how morepath works by looking at code (just like it does now). I fear quickstart already has more sidebars than it should have.

Maybe we can add it to the main page instead, below the "[More documentation, please!](http://morepath.readthedocs.org/en/latest/index.html#more-documentation-please)". We could have a "I just want to get knee-deep into code" kind of paragraph for people that want to skip reading and just want to run something and play around with it.

It definitely should be in the install docs though, there we could add it inside or above the "[Creating a Morepath Project](http://morepath.readthedocs.org/en/latest/index.html#more-documentation-please)" section.

**Comment by faassen** [comment]
Okay, that sounds fine with me. I just want to make sure people can't miss it.

**Comment by href** [comment]
Okay, I can have a stab at it later this week.

**Comment by href** [comment]
There we go: https://github.com/morepath/morepath/compare/cookiecutter-docs

**Comment by faassen** [comment]
This looks good! I think we should also add a note in "organizing your project". Something along the lines of "Help, I don't want to set this up by hand! You don't need to: cookiecutter recipe".

**Comment by faassen** [comment]
After you've added the note feel free to merge this into master yourself, by the way.

**Comment by href** [comment]
Done!
