### ISSUE TITLE
Release 0.12

### ISSUE THREAD

**Issue by href** [morepath/morepath#355]
Can we get a release for 0.12 on PyPI? I'm starting to rely on the new `request.after` behaviour :)
I can also do it if you want @faassen, I would just need maintainer rights on PyPI.

**Comment by faassen** [comment]
I will do this tomorrow. Maintainer rights I will also add then!

**Comment by href** [comment]
Awesome, thanks!

**Comment by faassen** [comment]
Do you have an account on readthedocs? I'd like to give you maintainer access there too.

**Comment by faassen** [comment]
pypi doesn't seem to currently want to let me into the edit page to give you access. I'll try again in a bit. The 0.12 release is done though.

**Comment by href** [comment]
Cool! My account name on readthedocs is 'href' as well.

**Comment by faassen** [comment]
Okay, all done now. You have readthedocs access for Morepath and Reg, and owner role for Morepath and Reg on pypi as well.

**Comment by href** [comment]
:+1: :sunglasses:
