### ISSUE TITLE
Morepath without Venusian?

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#358]
This is an idea I'd like to work out further, see where it goes. Morepath uses Venusian for two reasons:

* deferred decorators.

* scanning packages for modules with these deferred decorators.

Morepath's configuration engine however already *has* a deferred approach: when a decorator gets executed it could directly register a directive instance with the config engine. This in fact works this way already in tests as they can't use Venusian.

This implies we may be able to cut out Venusian altogether and just rely on Morepath's deferred story. This would mean that configuration directives are registered (but not executed) immediately during import time.

We would still need to supply a scanning function that can scan a package for Morepath related code, but that scanning function would simply do a recursive import to cause the configuration to be registered, and nothing else.

Cutting out Venusian has these benefits:

* tests are actually more in line with what really happens.

* slightly faster configuration time.

* I have a use case where people want to explicitly import those modules that use Morepath instead of automatically scanning. This would be easily supported without different ways of using Morepath; they'd simply not use the recursive package import but import explicitly before committing the configuration.

* we've been maintaining a fork for a while to support explicitly scanning a single module. Though the Venusian people are ready for merging it at last at this point, I think.

**Comment by faassen** [comment]
I've implemented an 'autoscan' package that just does recursive imports; I extracted the code from Venusian. I've also thought this whole change through a bit more.

The reason to do this is because Venusian is bothering some users; it's making debugging harder due to the indirection used (then again, Morepath can't remove all indirections here), and it's an expensive procedure in certain setups. It's arguable it's more clear to state that directives take effect upon import, just like any decorator in Python does.

Registration as a side-effect of imports means that Morepath needs to use a global configuration object, and it means that you cannot scan multiple times in a single process anymore -- once imported the registrations will have been made, and no more scanning can be done. Tests will need to be rewritten quite a bit as complete backward compatibility is not feasible. Real applications are least affected actually -- there is only one configuration registry in place in a real application.

Tests are affected in the following way:

* tests with inline decorators can become simpler. They shouldn't need a special `testing_config` declaration anymore. Instead of `config.commit` you'd write `morepath.commit()`.

* tests that scan fixture packages need to use something like `morepath.scan()` instead of `config.scan`,
  as the config object is going away. You cannot have multiple tests that reload the same fixture, but
  you could have this fixture shared between tests. Since these tests are in the minority I can deal with 
  them.

Production code that uses `autosetup` is unaffected. Production code that uses `autoconfig` or a manual config object is affected and needs to become something like:

```
morepath.scan('my_package')
morepath.commit()
```

or using manual imports entirely if you want to be explicit and have no dependencies:

```
import module1
morepath.commit()
```

I'm in two minds about this change; on the one hand I think it makes Morepath's behavior more predictable for newcomers, as imports will just work and you don't have to worry about weird scan stuff if you don't want to. On the other hand, there's more global configuration state where before that was nicely isolated in a separate object.

@href, I'd appreciate your feedback on this too.

**Comment by href** [comment]
I share your reservations about the introduction of more global state. Global state usually bites you in unexpected ways later down the line. But I also do like this being more straight forward and more in line with decorators, which is more obvious.

What might be a bit of a problem for me personally though is this:

> Registration as a side-effect of imports means that Morepath needs to use a global configuration object, and it means that you cannot scan multiple times in a single process anymore -- once imported the registrations will have been made, and no more scanning can be done.

I generate morepath applications dynamically as part of our database migration script by inheriting from existing applications that I don't know until my script is run. Basically I do this:

* Run the script with a list of applications (e.g. 'my.package.App', 'my.otherpackage.App')
* Inherit from each application inside a loop creating a short-lived upgrade application
* Scan the resulting upgrade application
* Open some view of the upgrade application

I basically do this to run a view in a script as if it was called from a browser.

Now there's probably other ways to do this, but I'm sure I'll find other uses for generating applications outside of tests and without knowing the involved packages beforehand. Is this still possible with the new approach?

I understand that you can only run the scanning once, but couldn't the committing be done multiple times? Would importing something after the configuration has been committed lead to an error? Like if I import package b after importing package b and committing.

Or am I not understanding this right?

**Comment by faassen** [comment]
Thanks for the feedback, @href! I'm trying to understand your dynamic application generation system. Does it generate Python code at some point? Or how do applications dynamically inherit? Why is it required to commit multiple times?

What should happen if you import something after the configuration has been committed is a good question. At this point you can scan things after a commit, and if you then recommit if I recall correctly it'll just throw away the old commit and do it again. This won't work if it's just an import, so I think this should raise an error to avoid confusion.

**Comment by faassen** [comment]
There are some other technical issues:

* Venusian has support for getting line number information out. This needs to be replaced by a hack that gets this information out from the Python stack. This should be doable however.

* Venusian avoids this problem: http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/designdefense.html#application-programmers-don-t-control-the-module-scope-codepath-import-time-side-effects-are-evil The new system needs to handle this issue too - recognize that the same module is imported twice and resolve it into only a single registration.

**Comment by href** [comment]
> I'm trying to understand your dynamic application generation system. Does it generate Python code at some point? Or how do applications dynamically inherit? Why is it required to commit multiple times?

I simply create new applications by creating classes inside a routine. So no there is no Python code generation. I commit multiple times because the views are configured on the class. You can see the whole thing here: https://github.com/OneGov/onegov.core/blob/master/onegov/core/cli.py#L307

> At this point you can scan things after a commit, and if you then recommit if I recall correctly it'll just throw away the old commit and do it again. This won't work if it's just an import, so I think this should raise an error to avoid confusion.

Why would this not work with the new system? I'm imagining that during import time some configuration-rawdata is gathered and during commit you use said data to apply the configuration. Couldn't you just re-apply the configuration every time you commit?

I'm speaking from a bit of a removed view, but assuming that configuration exists in some raw-state, we might also be able to use it for introspection and manipulate it before applying it. For example we could add views/paths to an existing application through function calls. Do I make any sense?

**Comment by faassen** [comment]
Ah, in your code you're using testing_config! I was already wondering how you'd generate configuration inline and have it be picked up all. Effectively by using testing_config you already skip using Venusian in this code and you're closer to the way it'd work without Venusian. In the new scenario you could make this work without using testing_config.

I'm curious you do a separate setup and config.commit for each application. Why is that necessarily instead of having a single one? Configs are already global in the sense that application objects magically gain access to them (because registrations are with the application object).

Concerning multiple commits: if you call commit a second time on a config object the previous configuration is entirely cleared and then the existing recorded directives is re-applied; I was mistaken in thinking a new scan is necessary. This functionality could indeed be retained.

**Comment by href** [comment]
> Ah, in your code you're using testing_config! I was already wondering how you'd generate configuration inline and have it be picked up all. Effectively by using testing_config you already skip using Venusian in this code and you're closer to the way it'd work without Venusian. In the new scenario you could make this work without using testing_config.

Ok good to know :). Sorry if I confused the issue a bit. I suspected this might play a role but I'm glad to hear you confirming that this works. So we can take this subject off the table.

> I'm curious you do a separate setup and config.commit for each application. Why is that necessarily instead of having a single one? Configs are already global in the sense that application objects magically gain access to them (because registrations are with the application object).

I am creating new applications with changing ancestors in a loop so I figured I need to scan each new application (so the views and paths get configured). Isn't the scanning needed for setting up the views and paths? The commit doesn't need to be repeated as I could just scan all the applications in a separate step and commit them all at once.

**Comment by faassen** [comment]
Aah, okay, I see you scan the modules needed too by some kind of magic based on their base classes.

I am wondering why you can't do a single setup(), then a scan_morepath_modules in the loop body, and a single commit after the loop. Do I get it right that you think that should work too? Your scan_morepath_modules might scan some of the same things multiple times, which might lead to conflicts, not sure.

**Comment by href** [comment]
> I am wondering why you can't do a single setup(), then a scan_morepath_modules in the loop body, and a single commit after the loop. Do I get it right that you think that should work too? Your scan_morepath_modules might scan some of the same things multiple times, which might lead to conflicts, not sure.

Yeah that sounds like it would work. But just to make sure I'm not overemphasising this feature: this is a script and if I can do this in another way I'm good too. I just want to keep this ability around in general.

At this point it would be great if you could create a preview branch where we can try this out. I would run this against our stack. If there are any other issues I'll discover them there. In principle I'm okay though. It's a trade-off to be sure, but it's more in line with how Python works, which is probably a good thing.

**Comment by faassen** [comment]
Thanks, you trying it with your stack would be very valuable! I agree a branch is needed next to try it out; I expect I'll start work on a branch on Monday. It could be I start feeling ambitious and pick up on my long-wished for "separate, documented configuration machinery library" project too, but we'll see.

**Comment by faassen** [comment]
Implemented via Dectate and merge into trunk now.
