### ISSUE TITLE
closed by default security policy

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#36]
Right now leaving out a permission means open by default. It should be possible to turn a knob and have everything without permission be closed by default. We could also tackle this in the directive implementation perhaps; if the knob is turned on,
the directive with complain if the permission is not specified.

**Comment by faassen** [comment]
@href, do you have more opinions about this now?

**Comment by href** [comment]
I stuck with the approach of having a test that asserts the presence of a permission on each view. It is *my* responsibility after all, whether Morepath helps me or not. Currently my approach is to intercept some Morepath calls. Though of course in the future I'll just query for it.

For us this didn't turn out to ever be an issue, so personally I don't have a need for a default permission. If you start adding permissions you have to kind of read about them in the docs though, so maybe we can add an example about how to write a test for it?

**Comment by faassen** [comment]
I wonder whether the query system could help querying for those views that don't have a permission set. I think it should be possible. Eventually we're going to have to document query system use cases...

Concerning an example on how to write a test for it, I'll add a note to issue #203
