### ISSUE TITLE
Add app.settings again

### ISSUE THREAD

**Issue by href** [morepath/morepath#366]
I was wondering if we should add `app.settings` again with the upcoming release. I know this was removed in an earlier release:

First we had `app.settings`
Which became `app.registry.settings`
Which will become `app.config.setting_registry`

I feel this is getting a bit too intricate. After all there are legitimate uses cases for wanting to access the settings (like https://github.com/morepath/more.transaction/blob/master/more/transaction/main.py#L48).

I also often feel more comfortable using the settings from the app than using `morepath.settings`, as `app.settings` is clearer than `morepath.settings()` imho.

If we reinstate `app.settings` we can at least provide a stable API to the settings through the application. At this point this API is too much of an implementation detail.

What are your thoughts?

**Comment by faassen** [comment]
+1 feel free to do a pull request for the dectate branch (is that possible? I want to merge the dectate branch into master very soon, you okay with that?), including a test, plus an update to the changes.

**Comment by href** [comment]
I think I can. Though I can also wait until dectate is merged. It's not a pressing issue for me.

As fior the merge: I have some feedback that I'll send your way this afternoon, though my tests pass at this point, so there's nothing major left.
