### ISSUE TITLE
Release 0.13

### ISSUE THREAD

**Issue by href** [morepath/morepath#368]
Anything holding us back from releasing 0.13 at this point? I think it's ready and it would fit my work schedule well if we released soon ;)

**Comment by faassen** [comment]
There are a few items on the milestone list I'd like to tackle, but instead I can move them into 0.14 and release 0.13 sooner. But if you're going to upgrade to 0.13 know you're the guinea pig. :)

Today I am finishing at least a first stab at a query tool infrastructure for Dectate. It needs a bit more polishing but I think it's good enough for a release. I'll do that first today and then move on to 0.13. Okay?

**Comment by href** [comment]
> But if you're going to upgrade to 0.13 know you're the guinea pig. :)

Sure, I don't mind :)

> I'll do that first today and then move on to 0.13. Okay?

Cool, thanks :)

**Comment by faassen** [comment]
It's out there... :)

**Comment by href** [comment]
:+1: - I went ahead and released a compatible more.transaction already.

**Comment by faassen** [comment]
Awesome!
