### ISSUE TITLE
document sample applications

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#376]
We have a bunch of sample applications in the repository. We should document them so we have a master list somewhere that people can look into.

**Comment by taschini** [comment]
I added a first draft, generated using the *description* metadata in the setup file of each example app in the umbrella project.

I put this draft on a separate page, ``examples``, and provisionally inserted this page after ``community`` and before ``installation``.

@faassen, the wording of the description definitely needs to be revised.  Would you mind editing it?

**Comment by taschini** [comment]
The wording of the descriptions of each of the examples. As I was saying they have been collected automatically from the setup files, and probably a human touch is needed to have a smooth text with a certain uniformity of style.

**Comment by faassen** [comment]
I've updated things (actually for 0.15), so will close this issue.
