### ISSUE TITLE
Redundant scans in test suite

### ISSUE THREAD

**Issue by taschini** [morepath/morepath#379]
It seems to me that quite a few of the importscan.scan invocations in the tests are redundant ([example](https://github.com/morepath/morepath/blob/43dd867f29701c19710cb3a44175b36f842a7cc2/morepath/tests/test_security.py#L139)). They might have had a purpose at the time when Venusian was used, I am not sure, but nowadays they mostly do nothing at all.

To improve the readability of the test suite, wouldn't it make sense to remove them?

[Update: fixed example link]

**Comment by faassen** [comment]
The example link is broken for me but I found the example.

Yes, that's a good point. We could indeed remove them when modules in the fixtures are used. The only place they have a role is where the fixture is an actual package. Feel free to send a pull request to remove them!

**Comment by taschini** [comment]
In [test_rescan in test_directive.py](https://github.com/morepath/morepath/blob/43dd867f29701c19710cb3a44175b36f842a7cc2/morepath/tests/test_directive.py#L1109), what is it that you are actually testing?

**Comment by faassen** [comment]
That you can re-scan a module without problems. It made more sense in the past but it's good to know it's still possible. We should also have another test where you import the same module twice for completeness. :)

**Comment by taschini** [comment]
All right. So, I moved test_rescan and and another test that was specifically addressing the scanning into a separate module (test_scanning.py). The latter and test_scenario.py are now the only modules where test cases explicitly perform any scanning.

**Comment by faassen** [comment]
Thank you, I merged this now. This kind of cleanup work is very valuable!

I'm curious to see what you're going to do next. :)
