### ISSUE TITLE
factor out basic auth identity policy into extension

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#381]
When I devised Morepath's identity/security infrastructure I included a basic auth policy, which also has a role in some of the tests. Since basic auth is almost always what you don't want I think it could live in an extension. That does mean that we rewrite some of the tests to use a dummy security policy that is similar to simpler to the basic auth policy and can live in the tests. It'd be a minor breaking change that needs to be explained in the CHANGES, including what action you should take (install ``more.basicauth`` and import from it).

Is someone interested in extracting it? 

cc @henri-hulski and @href as you both maintain auth related extensions.

**Comment by faassen** [comment]
To clarify on the tests. We need tests for the basic auth policy in ``more.basicauth``. But I also used the basic auth identity policy to write some tests for Morepath's security infrastructure and those need to be adjusted to use a dummy security policy that is similar to basic auth (without the specifics of encoding stuff) that can live in the tests.

**Comment by henri-hulski** [comment]
Not sure if anybody will use it ;-), but I can have a look.

**Comment by faassen** [comment]
Thank you! I figured we should still keep it as it's there and it can be useful in some circumstances, but it's indeed not worth it to maintain it as core Morepath.

**Comment by henri-hulski** [comment]
First  the question if basic auth is really secure and if it make sense to propagate it. 

Maybe better to advise using a more secure identity policy. 

But if you think using basic auth makes sense in some situations I can extract it. 
If not we can just get rid of it.

**Comment by henri-hulski** [comment]
Ok I see you already answered.

**Comment by faassen** [comment]
I am still considering. This argues against basic auth:

http://adrianotto.com/2013/02/why-http-basic-auth-is-bad/

But this argues *for* basic auth:

https://www.rdegges.com/2015/why-i-love-basic-auth/

I think getting rid of it in the core strikes the balance between the two -- we still support basic auth, but it's not in the core as the "recommended" option.

**Comment by faassen** [comment]
We also need to update the security.rst documentation. It should point to basic auth, and more.jwtauth and more.itsdangerous.

**Comment by faassen** [comment]
I'm working on the internals documentation for Morepath. I suspect once basic auth is extracted from ``security.py`` the rest of the module is entirely exported to the public API. I need to check though once it is done and make a note it is public in the ``implementation.rst`` doc. So leaving a reminder for myself here. :)

**Comment by faassen** [comment]
Oh, I'm wrong, the IdentityPolicyRegistry is not public so I will document it in internals already. So ignore that last comment. :)

**Comment by henri-hulski** [comment]
> To clarify on the tests. We need tests for the basic auth policy in more.basicauth. But I also used the basic auth identity policy to write some tests for Morepath's security infrastructure and those need to be adjusted to use a dummy security policy that is similar to basic auth (without the specifics of encoding stuff) that can live in the tests.

You already have a dummy  identity policy in [tests/fixtures/identity_policy.py](https://github.com/morepath/morepath/blob/master/morepath/tests/fixtures/identity_policy.py).

Is this one not sufficient?

**Comment by faassen** [comment]
You may be correct. But check the coverage for that module (how to generate it is in the docs) to make sure.

**Comment by henri-hulski** [comment]
If have created a pull request for the changes in Morepath.
It affects also test_querytool.py, where basic auth was used.
I fixed that, take a look, if it's ok.

`security.py` has a coverage of 100%.
But `_bytes()` from `compat.py` is not tested anymore.
The same with `isbaseclass_notfound()` from `directive.py`.
The later I don't know why.

By the way, I get a local test error in test_autosetup.py:21:
```
E           AutoImportError: Morepath wanted to import 'ns2' during auto-configuration, but
E           no such module could be imported.
```
and a travis flake8 error for `toposort.py`.

 [more.basicauth](https://github.com/morepath/more.basicauth) is also released.

Please take a look and tell me, if something should change.

So closing this!

**Comment by faassen** [comment]
Thank you very much! I cleaned up a bit of the documentation language plus the restructured text -- I found a few mistakes in my original text as well! :) I also had to remove ``morepath.security.BasicAuthIdentityPolicy`` from api.rst. You can create the docs using bin/sphinxbuilder and see errors, though currently unfortunately a generic dispatch function generates a warning it shouldn't.

I don't see the test_autosetup.py issue  -- how do you set up your testing environment?

The toposort issue I fixed, dangling newline at end of file...

P.S. In the future let's close the issue after the pull request is merged/the review of the branch is done, then we know we properly finalized the project. I had to go searching through the issue tracker to find your comment here.

**Comment by henri-hulski** [comment]
> I cleaned up a bit of the documentation language 

I like your language  -  one reason I found Morepath. 
I'm not so talented. 

> You can create the docs using bin/sphinxbuilder

No experience yet with Sphinx. I think I should try it out. 

> how do you set up your testing environment

Exactly as described in the docs. 

> let's close the issue after the pull request is merged

Sure. By the way, I always click the `view it on GitHub` link in the email notification, which leads me directly to the issue.

**Comment by henri-hulski** [comment]
And I'm using Debian Jessie with Python 2.7.
