### ISSUE TITLE
recursively commit for mounted apps

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#383]
Spun off from #378, quoting @taschini:

> Actually, I think there is a way forward. We need first something like an app.commit_configuration
>  class method that does the kind of recursive discovery and commit that you described (and
>  motivated) above.

> That would allow a line like the following:

> ```dectate.commit(app.Root, app.Generic, app.Document)```

> to be replaced by

>    ```app.Root.commit_configuration()```

> Similarly for the tests in test_mount_directive.py.

> I think this first step is worthwhile even without the next step, which would have the app instance to 
> invoke it unless is_committed() at some point before the first __call__().

**Comment by faassen** [comment]
I thought about this before but thought it would only be useful if app instantiation triggered commit, but you're right that it's useful already. A few points:

* the class method that gets the list of additional apps to commit should be a hook that
  Dectate uses and Morepath plugs into. Morepath then extracts the required information
  from the mount registry.

* we should just call it `dectate.App.commit()` and make it a class method.

* there is a problem: if you use this with autocommit and you have a mounted app, then you'd 
  repeatedly commit the same  App - once in autocommit and once recursively. This will work but
  there is a performance cost. Avoiding it could be done with is_committed checks, but we want to
  be careful with that too, because right now I consider it to be a usecase to be able to recommit 
  configuration after expanding it, and I believe I even have a test for that. Should `App.commit()` 
  check for `is_committed` but `dectate.commit` should not? Hm, maybe ``autocommit`` is the
  one that should not re-commit if `is_committed` is True, and the others should all recommit.

**Comment by faassen** [comment]
So we'd have:

* dectate.commit(App): commit this app, don't recurse. No check for is_committed.

* dectate.App.commit: commit this app and any dependent apps, where dependent is defined by
  client code such as Morepath. No check for is_committed.

* dectate.autocommit(): commit all known apps, but check for is_committed so that an app previously
  committed because of a recursive commit is not recommitted. Writing a test for this is going to
  be painful, as writing a test for autocommit is already painful. I think we should split off a separate
  function that does the equivalent of autocommit but gets an explicit lists of apps to commit and
  build autocommit on top of that.

**Comment by faassen** [comment]
All of this should actually become a Dectate issue. :)

**Comment by taschini** [comment]
That's probably too ambitious to do in one go.

1. I'm willing to write a ``morepath.app.commit()`` class method as a first step.  
2. Once that is working and tested we can refactor it as a ``dectate.app.commit()`` + hook.  
3. Then only if we see that there is a significant performance cost in the startup phase with the issue of multiple commit, we can optimize it with a ``dectate.autocommit()``

**Comment by faassen** [comment]
The autocommit optimization needs to be done -- a combination of mounted apps and autocommit happens in the real world and we don't want a normal use already result in duplicate commits. It's not just an optimization, it's also for the sanity of a developer going in with a debugger and seeing the exact same thing happening multiple times.

I'm happy if this is implemented step by step on a branch, but I do want to merge the whole thing into Dectate as a whole.

**Comment by faassen** [comment]
By the way, your wording is "optimize it *with* a dectate.autocommit()", which I'm confused about. There's already an autocommit and it needs to be optimized in the sense that it won't recommit anything that has been committed otherwise. I think there are no good use cases for calling autocommit multiple times in real-world code anyway.

**Comment by taschini** [comment]
> By the way, your wording is "optimize it with a dectate.autocommit()", which I'm confused about. There's already an autocommit and it needs to be optimized in the sense that it won't recommit anything that has been committed otherwise. I think there are no good use cases for calling autocommit multiple times in real-world code anyway.

I'm sorry, I wasn't aware of the existing ``dectate.autocommit`` and had therefore misunderstood your remarks about it.

> a combination of mounted apps and autocommit happens in the real world and we don't want a normal use already result in duplicate commits

Adding this ``morepath.app.commit()`` class method does not affect existing code. You would still be perfectly free to keep on using ``dectate.commit(app, ...)`` and ``dectate.autocommit()`` should you so prefer.

If I correctly understand, these correspond to three different use cases:

1. Commit all apps: use  ``dectate.autocommit()``
2. Commit all the apps I need and I am telling you what are the apps that I need: use ``decate.commit(app,...)``
3. Commit all the apps that are needed to run ``app1`` and I'll let you figure out which these apps are: use ``app.commit()``.

**Comment by faassen** [comment]
Yes, and I just realized that since ``dectate.autocommit`` uses ``dectate.commit`` it is not affected by the recursive commit story at all. So no change needs to be made after all. :)

While ``dectate.commit`` is still a useful API it should have less prominence now in the Dectate documentation and tests and we should favor ``App.commit``. Similarly in the Morepath tests. In Morepath we already have ``autosetup`` as the "easy way in", which uses autocommit, and I think we should stick to that for now, but we should document ``App.commit`` as the explicit alternative and for testing purposes.

**Comment by faassen** [comment]
Okay, this works now, thanks @taschini !

I'll leave another issue in Dectate to implement a simpler ``commit`` method there.
