### ISSUE TITLE
rename morepath.security to morepath.authentication

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#384]
``morepath.security`` only contains the authentication system for Morepath based on identities, and permission infrastructure is implemented elsewhere, so I think it would be clearer to rename it to ``morepath.authentication``. We would break imports from ``morepath.security`` which are currently advertised in the public API, but I already moved some of those into ``morepath`` as they should have been, and the basic auth stuff is going to be removed, see #381.

**Comment by href** [comment]
It would be nice if supported both names for one release and include a deprecation warning. Not really necessary because we're not at 1.0 yet, but I think it's a good habit.

**Comment by henri-hulski** [comment]
Good idea. I was also irritated by Security. Authentication is much more clear. 

Would be nice to have this soon, as I need it also for basic auth imports.

**Comment by faassen** [comment]
I can do it monday but if you want to do it before feel free. We just need to be clear about changes and update the docs.

Concerning keeping a compat shim in place as @href suggested, I am +0 on that, I rather like not having compat cruft plus it is not hard to explain what to do to upgrade code, on the other hand it is a nice service to deprecate. We just need to be aggressive anout removing stuff we deprecated otherwise it will stick around for years.

**Comment by henri-hulski** [comment]
I have released more.basicauth and created a PR for morepath.
So I think you should merge this first and after rename.
I will adjust it then for more.basicauth and more.jwtauth.

**Comment by faassen** [comment]
I'm doing the renaming now, but I'm including deprecation warnings so we get some experience with the best way to use them. We should remove these again by Morepath 0.15 so we don't have them cluttering up stuff.

**Comment by faassen** [comment]
Concerning more.basicauth and more.jwtauth, these should be importing directly from the ``morepath`` namespace instead of ``morepath.authentication``.

**Comment by faassen** [comment]
Okay, I've done the renaming and got some practice concerning our deprecation policy. I'll open a new issue for this to discuss that.

**Comment by faassen** [comment]
I'll leave this issue open and reassign to @henri-hulski so he can update the remaining more.* auth packages to the new API.

**Comment by henri-hulski** [comment]
> Concerning more.basicauth and more.jwtauth, these should be importing directly from the morepath namespace instead of morepath.authentication.

Actually they was. I had only to change some references in the docstrings.

@href 
There were also a few references to `morepath.security.Identity` in more.isdangerous so I created a PR.

**Comment by faassen** [comment]
Thank you! I'll close this now, we just need to remember to releases these after the new release. I will make an issue to track what we need to re-release.

**Comment by henri-hulski** [comment]
Actually no need to do so.
The changes are backwards compatible as morepath.identity etc exists before.

**Comment by henri-hulski** [comment]
I mean we can release them before morepath.
And it's only urgent for more.isdangerous as the others have only changes in docstrings.
