### ISSUE TITLE
should NoIdentity be part of the public API?

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#385]
Need to dig through ``security.py`` to see whether we can currently define permissions that are only true if the user has no identity, and whether the ``NoIdentity`` class is useful in that. There is no test of this right now. If so needs to be documented and become part of the public API. If not needs to be documented in the private API.

**Comment by faassen** [comment]
It isn't needed to expose ``NoIdentity`` as passing ``None`` into ``permission_rule`` uses it already. So closing.

**Comment by henri-hulski** [comment]
In basicauth and jwtauth I return NO_IDENTITY, when user cannot identify. 

Should I change this to None?

**Comment by faassen** [comment]
No, NO_IDENTITY is fine, part of public API. I was just wondering about its class, which isn't.
