### ISSUE TITLE
release extensions for 0.14

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#393]
We need to release versions of more.jwtauth and more.itsdangerous compatible with 0.14. See #384 

We also need to release more.forwarded, see #271

**Comment by henri-hulski** [comment]
We can release more.itsdangerous before morepath as `morepath.identity` is backwards compatible.
The same for more.jwtauth and more.basicauth, but they have only changes in the docstrings so they break nothing.

**Comment by href** [comment]
A new [more.itsdangerous](https://pypi.python.org/pypi/more.itsdangerous/0.0.2) release is out. Thanks @henri-hulski

**Comment by faassen** [comment]
I need to release a new more.static as I changed an import location.

**Comment by faassen** [comment]
New more.static is released; could be released as it didn't break compatibility importing the reg registry from ``morepath.directive``.

**Comment by henri-hulski** [comment]
more.basicauth 0.2 and more.jwtauth 0.5 are released.

**Comment by faassen** [comment]
Thanks @henri-hulski !

**Comment by faassen** [comment]
I think all extensions are ready for release then!
