### ISSUE TITLE
reuse topological sort from Dectate

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#403]
Officially publish it as part of the dectate API and use it. Same with the error. This should also
fix this issue brought up by @henri-hulski :

> is there a reason why you declare TopologicalSortError 2 times, in error.py and toposort.py?

**Comment by henri-hulski** [comment]
To be more clear, both error declarations are in dectate.

**Comment by henri-hulski** [comment]
`TopologicalSortError` actually is declared 3 times: in `dectate.toposort`, `dectate.error` and `morepath.error`.

**Comment by faassen** [comment]
Thanks to @taschini this has now been sorted out.
