### ISSUE TITLE
Update the quickstart

### ISSUE THREAD

**Issue by taschini** [morepath/morepath#406]
Following #392 autocommit should be removed from doc/quickstart.rst:

- Remove autocommit invocation from from doc/code_examples/hello.py.
- Remove point 6 and defer its message to rst/organizing_your_project.rst.

Additionally, I noticed that the output of 

```
$ python hello.py
```
is actually more similar to

```
Running <__main__.App object at 0x110c61090> with wsgiref.simple_server on http://127.0.0.1:5000
```

instead of what is in doc/quickstart.rst:

```
Running <morepath.App 'Hello'> with wsgiref.simple_server on http://127.0.0.1:5000
```

Should we add a `morepath.App.__repr__` method?

**Comment by faassen** [comment]
Hm, I think the quickstart reference 'hello' is actually out of date to the era where we still associated configuration with app instances instead of app classes. So I think it'd be better to update the quickstart instead of adding a ``__repr__``, especially as I don't see how that ``__repr__`` could work.

**Comment by taschini** [comment]
Well, as the quickstart would need to be updated anyway, one could take this opportunity to add a `__repr__` to morepath.App, one which could look more pleasant to the eye and be more useful than the C  pointer to the object — Anyway, this point is actually fairly minor, and came up only because one of my extra tests showed the inconsistency.

Any opinions on the other two points?

**Comment by faassen** [comment]
I'm happy to introduce a more useful ``__repr__``, just curious what it would look like. The C reference is actually conceivably useful when you do debugging of mount scenarios.

**Comment by faassen** [comment]
Oh, yes, I agree we should remove any references to autocommit from the narrative docs, including this one. Sorry for not making this clear, I agree with the general premise of this issue. :)

**Comment by faassen** [comment]
(I *did* add it to the 0.14 milestone for that reason!)

**Comment by faassen** [comment]
This got merged.
