### ISSUE TITLE
update the morepath example applications to follow cookiecutter-style setup

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#411]
Now that we have a cookiecutter setup we should update the example applications to follow a similar setup, with install instructions in README.txt. The sample applications right now use buildout and depend on development versions of Morepath, but that's not really useful anymore. We should also retire any example applications that have served their purpose.

Spun off from #404

**Comment by faassen** [comment]
A nice opportunity to implement #286

**Comment by taschini** [comment]
All example in #434  have now been updated in this respect. AFAICS this issue can now be closed.
