### ISSUE TITLE
morepath.autorun

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#416]
This won't work for real deployment, but we could provide a ``morepath.autorun(App)`` that does an autoscan, a commit of the app class, instantiates it and calls ``morepath.run`` on it. This would simplify setup code in examples, while still doing an automatic commit *before* running (so that conflict errors are detected immediately).

We could also provide a ``App.autosetup`` that does an autoscan before it does a commit so it makes the app entirely ready to run.

I'm not sure whether any of these are a good idea because it just gives more options and only saves a few lines of code.

**Comment by href** [comment]
Personally I don't have the need for this. Except for tutorials the builtin WSGI runner is too basic for my use.

I also wouldn't hide the fact that we need an instance of the App to run it. This is true for any WSGI server, be it development or deployment and it is something anyone seriously using Python in web development has to learn one way or another.

So that's a -1 from me ;)

**Comment by taschini** [comment]
That's a -1 from me too, for pretty much the same reasons.

**Comment by henri-hulski** [comment]
Maybe we could create a simple CLI to create a new app and run it.
For creating the app we can just use the cookiecutter and for serving something like you said above.

Like this it would be decoupled from the Morepath API and I think it's mostly useful for people, who starts with morepath.

The Cerebral guys just created a similar CLI and there is a nice talk about the pros and cons of it at
https://plus.google.com/events/c3q2jan8jhst2po6r1l50dcm1s8 at 30:30.
(BTW at the beginning of the video there is some interesting technical explanation of context providers, which was separated and refactored for Cerebral 0.34).

For now their CLI actually allows to create a new app and serve it and create some modules inside the app (this doesn't worked with me).

**Comment by faassen** [comment]
Closing this issue. I think it's an inappropriate reaction to the problem I see with #392
