### ISSUE TITLE
remove autosetup from demo code

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#419]
We have demo code in the morepath repository that uses autosetup. Since as of Morepath 0.14 this is now deprecated and we want to remove the API as of Morepath 0.15, we should update our demo code.

**Comment by faassen** [comment]
While you're add it create a list for #376 :)

**Comment by henri-hulski** [comment]
You're talking here about the sample applications or example code in morepath documentation?

I think you mean the sample applications, as you are linking to #376.

The list of sample applications I found is:

* morepath_cerebral_todomvc
* morepath_reactredux
* morepath_hello
* morepath_batching
* morepath_react
* morepath_sqlalchemy
* morepath_rest
* morepath_static
* morepath_demo
* morepath_wiki

Do you want to keep them all or are some of them outdated?

I just created a task list for this, #411 and #376.

@faassen: If you want to remove some, tell me.

**Comment by faassen** [comment]
Sample applications, not sample code in the docs. I think we should probably retire quite a few of these examples, I need to go through them to see which can survive.

**Comment by henri-hulski** [comment]
There's also [whatsitdoing-morepath](https://github.com/morepath/whatsitdoing-morepath). 
But I think it's more for profiling.

**Comment by faassen** [comment]
I updated whatsitsdoing-morepath just now, ran another benchmark and included the results in the README.

**Comment by taschini** [comment]
The work in #434 related to this issue is done. And I can confirm that ``autosetup`` is no longer present  in the demo apps listed in #434.

As far as I can see, this issue can be safely closed.

**Comment by faassen** [comment]
Okay, closing this issue. Thank you everybody!
