### ISSUE TITLE
Content negotiation? 

### ISSUE THREAD

**Issue by estebistec** [morepath/morepath#424]
Following the docs for [views / render](http://morepath.readthedocs.io/en/latest/views.html#render) I find a simple example for providing different formats on a model:

```python
@App.html(class=Document)
def document_default(self, request):
    return "<p>Some html</p>"

@App.json(class=Document)
def document_default(self, request):
    return {'my': 'json'}
```

Makes sense. I would expect this would cause the server to provide more options in content negotiation. I assume `class` is a typo for `model`. So trying the following example...

```python
import morepath

class App(morepath.App):
    pass

@App.path(path='')
class Root(object):
    pass

@App.html(model=Root)
def hello_world(self, request):
    return "Hello world!"

@App.json(model=Root)
def hello_world_json(self, request):
    return {'message': "Hello world!"}

if __name__ == '__main__':
    morepath.autocommit()
    morepath.run(App())
```
However when I try to run this app it dies with:

```shell
Traceback (most recent call last):
  File "hello_morepath.py", line 80, in <module>
    morepath.autocommit()
...
dectate.error.ConflictError: Conflict between:
  File "hello_morepath.py", line 12
    @App.html(model=Root)
  File "hello_morepath.py", line 16
    @App.json(model=Root)
```

`morepath`  version is:

```shell
(morepath-sandbox) ➜  morepath-sandbox pip freeze -l | grep morepath
morepath==0.13.2
```

So, pretty straightforward question: supported or no? I see other examples where the alternate media types have additional path "names", but I'd rather not couple my media types to URL patterns. Is the example outdated? Have I done something silly or botched the example?

**Comment by href** [comment]
As of now we do not support this use case. So you did nothing wrong, it's working as expected.

Personally I just use different urls (say `/posts` and `/posts.json`), but I agree that this is a personal preference. We had some previous discussion on this subject though:

https://github.com/morepath/morepath/issues/70

The referenced ticket includes some ideas on how to solve this. If you're interested in helping I'm sure there's a way it can be implemented and/or documented.

Feel free the reopen said ticket if you want to have it discussed further.  I'll close this ticket for now to keep the discussion in one place.

**Comment by faassen** [comment]
Morepath's predicate system does support the introduction of a new predicate to do content-negotation. I'd like to see an extension that installs this predicate. Please let me know if you need help implementing the predicate; I think there is some trickiness in how to properly deal with the Accept header, so I hope it's doable:

http://morepath.readthedocs.io/en/latest/views.html#predicates

**Comment by faassen** [comment]
@estebistec I'll open that ticket for you actually, as to make it easier for you.

**Comment by estebistec** [comment]
Thanks, I'll have a look at it.
