### ISSUE TITLE
settings_sections directive

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#430]
There's the use case where the developer wants to read settings from a file. Currently you could use ``setting`` or ``setting_section`` to parse a file and introduce settings. But what if you have multiple setting sections in a file? Reloading and reparsing the settings file isn't ideal.

We could introduce a ``setting_sections`` directive, better name perhaps ``load_setting_sections``, which lets you return multiple setting section dictionaries in a list. These get inserted into the settings object. They're overridable as before, as this is implemented using a composite action on top of ``setting_section``.

In ``inject_setting_sections`` you could inspect the command line args or environment to determine the settings file, and then load it and parse it into a list of setting section dictionaries. This gives the developer a canonical place to do this. We should document this as the regular pattern giving an example that uses configparser. Using this directive you can even develop a framework app base class that has some default behavior baked in.

**Comment by href** [comment]
I like it! One question: How would you inspect the command line args given? Since those should be outside Morepath's control, I don't see how you could access them.

Could we maybe pass custom arguments or your proposed settings directory to the application during commit or through some other mechanism? Then it doesn't matter where they come from and we can use whatever mechanism we like.

**Comment by henri-hulski** [comment]
Sounds interesting. 

Like this it would be possible to set some default settings for an App in a configuration file and allow the developer/administrator  to change them to their needs. 
And organize them in sections. 

I think this is really a useful feature.

**Comment by faassen** [comment]
Wouldn't we always be able to rely on sys.argv, they are global anyway, right?

@henri-hulski the setting and setting_section directive can already do this, so this isn't entirely new. the focus here is on loading the config from a file in a directive.

**Comment by href** [comment]
> Wouldn't we always be able to rely on sys.argv, they are global anyway, right?

Sure, but then we are moving the handling of sys.argv inside our web application, which seems a bit weird. If we have the ability to just pass in a dictionary we are pretty free in how we acquire it. In the simplest a script could just parse a config file and turn that into a dictionary.

**Comment by faassen** [comment]
The alternative to doing this in a directive is to have a way to pre-fill the settings before the app is started; a runaround to a directive that then has to return setting sections seems to be overly complicated to me. This pre-fill story would issue a whole bunch of programmatic ``SettingAction`` objects so that the override system still works.

**Comment by henri-hulski** [comment]
Maybe it makes sense to implement 2 directives.

One lower level which excepts a dictionary with the settings and merge it in the settings when the app gets started. This dictonary can be received for example by parsing a config file or querying a database.

The other one which works out of the box by just giving him the path to a config file lets say written in YAML or even Python. In the later case you can use a dotted path and include other files.

Overriding applications should be able to override the settings with their own.

**Comment by faassen** [comment]
@henri-hulski I think a directive that loads configuration out of the box from a ConfigParser or YAML file or whatnot would be useful, but it would probably have to be in an extension to Morepath. I would like to investigate what we would need to support in core Morepath to make such extensions possible and easy.

The low-level API would indeed get a dictionary of setting sections which contain dictionaries of settings. It would be implemented as a bunch of setting_section actions issued against the app programmatically. This means it needs to be called before committing the app.

**Comment by faassen** [comment]
I think the low-level API wouldn't be hard to implement, and I think we should go for it, no matter what we decide about the fancier directive-based option.

**Comment by henri-hulski** [comment]
Not sure if this fits here but I just recall our discussion about Settings for identity policy #309.

Just two of the last comments:

> henri-hulski commented on 17 Apr 2015
> Also interesting that we have here a clear lookup path for the settings through the app without passing it as an argument even in explicit mode.
> Actually I still not entirely understand the lookup system, but I think that for the settings we don't need >the flexibility to choose the lookup mechanism.
> As I understand in morepath you use app.lookup and request.lookup but the settings should be rather bond to the current app. 
> Please tell me if I'm wrong.
> Now with the new feature it seems, that we do exactly that. Binding the settings for the identity policy to the current app.
>
> I wonder if something like this would be possible for the entire setting system or if there are use cases, where we need different lookup mechanism for settings.

and your answer (recently):

> faassen commented 28 days ago
> @henri-hulski if you're still interested open another issue discussing your idea for accessing settings through the app or request everywhere. It may indeed be possible to be explicit throughout, I'm not sure whether there are exceptions.

Maybe this ideas are useful while implementing this low-level API.

**Comment by faassen** [comment]
I'm not entirely sure it's relevant, @henri-hulski but @href reintroduced ``app.settings`` as a way to get the settings recently. So I think we can already do this. See #366

**Comment by faassen** [comment]
So what should the API look like? Something like this:

```
App.initialize_settings({'foo': {'enable_foo': True, 'engine': 'ADVANCED'}, 'bar': {'space': 'huge', 'security': False}})
```

this would call ``settings_section`` for ``foo`` and ``bar`` on ``App``. This will generate the proper configuration actions which can act as normal, can be overridden, etc.

**Comment by href** [comment]
I think this would be a reasonable API. I was wondering if we needed a way to evaluate sections lazily, but it's not like we can do that with regular settings now.

Also, how about shortening it to `App.init_settings`? Then we don't have to decide if we use American or English spelling for "initialise".

**Comment by henri-hulski** [comment]
I think this is the most obvious way to do it.

**Comment by faassen** [comment]
``App.init_settings`` it is.

**Comment by faassen** [comment]
This should include some documentation that at least describes a way to integrate this with config parser. Or possibly a little extension that helps.

**Comment by faassen** [comment]
Any one want to take this one?

**Comment by henri-hulski** [comment]
@faassen I can have a look.
