### ISSUE TITLE
Have morepath.run find an unoccupied port in a given range

### ISSUE THREAD

**Issue by taschini** [morepath/morepath#439]
The function ``morepath.run`` is not meant for deployment, however it features in all example applications, where it is used for debugging and exploration.

The current signature is, effectively, the following:

```
def run(wsgi, host='127.0.0.1', port=5000):
```

If the given port is occupied by some other service, ``morepath.run`` fails, and quite uncouthly at that.  Since for a new developer using Morepath ``morepath.run`` is usually the first interface by which Morepath is explored, I think it would be better if morepath.run would find an alternative port to use instead of failing.

Therefore I suggest to change the effective signature of ``morepath.run`` to

```
def run(wsgi, host='127.0.0.1', port_range=range(5000, 5020))
```

(In practice the actual default for ``port_range`` will be ``None``, which will be replaced by the range inside the function body.)

If all ports in the given range are already in use, ``morepath.run`` will print a message and return -1.  Bear in mind that ``morepath.run`` is meant to be used for a script entry-point and print + return code is more appropriate in this context than throwing an exception.

This change breaks API compatibility. However, in the example applications ``morepath.run`` is always invoked with default values, so no change in those apps is needed.  At the same time, this is yet another reason in favour of this change, as otherwise attempting to run more than one of the examples at the same time will fail.

Since deployed apps should not be using ``morepath.run`` anyway, I don't see many disadvantages in going forward with this change.

**Comment by href** [comment]
I'm rather -1 on this change. I see two problems:

* The user already started morepath.run in another window and the second invocation leads to two instances being run, one of them being outdated.
* We can't document "run this and then open localhost:5000", we always need to explain that they first have to find out what port was actually chosen.

Are there any other web frameworks that do this?

**Comment by faassen** [comment]
Agreed with @href, -1 as it is too clever and can be confusing. Most systems generally take a single port number and fail otherwise. If the error message  when a port is in use is confusing lets fix that.

**Comment by taschini** [comment]
Well, even now the first thing that `morepath.run` does is to print the URL on which it is listening. So we could simply instruct people to "run this and then follow the link printed on the console."

Anyway, if you guys reject this proposal, I think you should then at least modify the example applications, or the cookiecutter template, so as to provide a way for people to run the app on a different port:

* You might already have another service running there,
* You might be comparing Morepath to Flask (which also uses port 5000 by default),
* You might be comparing morepath_cerebral_todomvc and morepath_reactredux.

The error message must then be tailored to the solution that is adopted, e.g.:

```
Port 5000 is already in use.  Specify an alternative port with --port
```

See also 
* http://flask.pocoo.org/snippets/133/
* http://www.speedguide.net/port.php?port=5000

**Comment by href** [comment]
That sounds more reasonable to me. A good error message and a way to solve the problem.

**Comment by faassen** [comment]
Having a port argument and better error sounds good. Doesn't need to have extra code in the examples; we can do argparse for --port in ``morepath.run`` and override the default.

**Comment by henri-hulski** [comment]
> provide a way for people to run the app on a different port

I think `run-app --port=5500` already works,  doesn't it? 

So maybe it's a good idea to mention in the README, that you can run it on another port and to have an informative error message is also a good idea.

**Comment by taschini** [comment]
> I think run-app --port=5500 already works, doesn't it?

Well, as far as I can see with [morepath_cerebral_todomvc](https://github.com/morepath/morepath_cerebral_todomvc/tree/f070f6b22b6a16b8f0a5c56ac916fa9c8fa40d0a) with more path 0.14, no, it doesn't. It ignores any arguments on the command line and listens to port 5000. Here's a copy of my virtual environment:

```
dectate==0.10.2
importscan==0.1
morepath==0.14
-e git+git@github.com:morepath/morepath_cerebral_todomvc.git@f070f6b22b6a16b8f0a5c56ac916fa9c8fa40d0a#egg=morepath_cerebral_todomvc
reg==0.9.2
repoze.lru==0.6
WebOb==1.6.0

```

**Comment by henri-hulski** [comment]
It seems, that you're right. So this was with another server.
In this case I think providing a port argument makes really sense.
As a developer you are working sometimes on several applications at the same time or compare them, so this should be possible.

[waitress-serve](http://docs.pylonsproject.org/projects/waitress/en/latest/runner.html) takes a port argument like `waitress-serve --port=8041`.
So I think we can implement it in a similar way.
Actually I would prefer `run-app --port 5500` without `=`.

**Comment by henri-hulski** [comment]
The code of [waitress-serve](http://docs.pylonsproject.org/projects/waitress/en/latest/runner.html) is here:

https://github.com/Pylons/waitress/blob/master/waitress/runner.py

It seems not to complicated and provides also a help message if something goes wrong.

**Comment by henri-hulski** [comment]
I just realized, that we don't use waitress, but wsgiref.simple_server.
So this gonna be different, but maybe we can still use it as inspiration.

**Comment by taschini** [comment]
So it seems a consensus is slowly emerging. What about the following, then:

```
def run(wsgi, argv=None, default_host='127.0.0.1', default_port=5000):
    if argv is None:
        argv = sys.argv
    …
```

where we support two command-line options, `--port` and `--host` and whose defaults are specified by the respective arguments to `run`.

**Comment by henri-hulski** [comment]
Default host and port are already set in `morepath.run`.

This works:
```
import argparse
import morepath

from .app import App


def run():   # pragma: no cover
    parser = argparse.ArgumentParser()
    parser.add_argument("-H", "--host")
    parser.add_argument("-p", "--port", type=int)
    args = parser.parse_args()
    morepath.autoscan()
    morepath.run(App(), host=args.host, port=args.port)
```

**Comment by faassen** [comment]
No argv argument to run() I think.  Instead an explicit port arg defaulting to None. If None is given use argparse to parse the commandline arg, this uses global info but for morepath.run this is fine. If no commandline arg given default to 5000. Argparse lets you provide a default. If explicit port arg is there that always trumps commandline.

**Comment by henri-hulski** [comment]
Like the above we get 3 command line options:

*  -H or --host for the host
*  -p or --port for the port
*  -h or --help for a little help

**Comment by taschini** [comment]
Let's not bikeshed over details.

**Command-line interface** As Henri says, three options (--port/-p, --host/-H, --help/-h)

**API** As Martijn says, it shold be possible for arguments to `morepath.run(wsgi, ...)` to trump CLI arguments.

Everybody agree?

**Comment by henri-hulski** [comment]
> API As Martijn says, it shold be possible for arguments to morepath.run(wsgi, ...) to trump CLI arguments.

Don't understand this. I think command line options should override function arguments, right?

If you're agree I can make a PR (actually prepared one).
Or you make it if you have one.

**Comment by henri-hulski** [comment]
@faassen and @taschini 
I mean when you specify on the command line an argument normally this has priority from the one provided by the program. Or have you a reason to do otherwise?

**Comment by taschini** [comment]
I agree, Henri, that the command line arguments normally have the priority over the values specified in the program.  This is the reason why we have command-line arguments in the first place.

What I was referring to was simply that you need a way to optionally disable command-line argument parsing in `morepath.run()`, i.e., a way to say the the `host` and `port` arguments are authoritative, and ignore whatever is specified on the command line.

A suggestion for the signature of `morepath.run` could then be

```
def run(wsgi, host='127.0.0.1', port=5000, use_argv=True):
    pass
```

In this case if `use_argv` is True, the values passed to `host` and `port` are then used as defaults for the `argparse` parser and the command-line is authoritative.  If the `use_argv` is False, the actual parameters passed to `morepath.run` are authoritative, and the command-line arguments are ignored.

One might object to using a boolean parameter in this way, and that a better API would provide two separate functions for these two behaviors (the names I picked here are just for demonstrative purposes):

```
def run_with_argv(wsgi, host='127.0.0.1', port=5000):
    pass

def run_no_argv(wsgi, host='127.0.0.1', port=5000):
    pass
```

**Comment by henri-hulski** [comment]
Sounds reasonable. 
I just can't imagine a use case when you want the command line arguments to be ignored. 
Maybe you have an example?

**Comment by taschini** [comment]
Suppose, for instance, that you are testing your app with `py.test` driving [Selenium](http://selenium-python.readthedocs.io/index.html).  If you don't provide a convenient way to ignore the command line arguments, `morepath.run()` would choke on the `sys.argv` that py.test receives.

More in general, whenever `morepath.run` is used in an automated test suite.

**Comment by henri-hulski** [comment]
Ok, i think this makes sense.

**Comment by henri-hulski** [comment]
I have no experience with advanced test scenarios. Just wondering where in this case the sys.argv are coming from. 
They're send by the test suite?

**Comment by taschini** [comment]
Generally speaking, `sys.argv` is left untouched.  So if you invoke your test-suite as

```
$ py.test -sx tests/browser_emulation/ --cov app
```

``morepath.run`` will see `['py.test', '-sx', 'tests/browser_emulation/', '--cov', 'app']` as `sys.argv`

**Comment by henri-hulski** [comment]
Got it.
Am 06.05.2016 11:35 schrieb Stefano Taschini <notifications@github.com>:Generally speaking, sys.argv is left untouched.  So if you invoke your test-suite as

$ py.test -sx tests/browser_emulation/ --cov app


morepath.run will see ['py.test', '-sx', 'tests/browser_emulation/', '--cov', 'app'] as sys.argv

**Comment by faassen** [comment]
So we can close this, correct?

**Comment by taschini** [comment]
I think so.

**Comment by faassen** [comment]
Thanks everybody!
