### ISSUE TITLE
Deprecation of remember_identity,  forget_identity, settings

### ISSUE THREAD

**Issue by taschini** [morepath/morepath#446]
The ideas is to deprecate these pluggable functions that are part of the public API of ``morepath``:

1. ``morepath.settings`` in favor of the existing ``morepath.App.settings`` property.

2. ``morepath.remember_identity`` in favor of a new ``morepath.Request.remember_identity`` method.

3. ``morepath.forget_identity`` in favor of a new ``morepath.Request.forget_identity`` method.

The choice of ``morepath.Request`` as the recipient for the new methods is due to the request class being a proxy for the overall context, but I have no objection to have ``morepath.Response`` as the recipient instead.  For ``forget_identity``, for instance, one could have either of the following:

* ``request.forget_identity(response)``
* ``response.forget_identity(request)``

I have a preference for the former, but I'd be fine with the latter too.

**Comment by faassen** [comment]
#448 implies we need to add these methods to the app class, not the request. Once #448 is implemented this would be done directly in fact.

**Comment by taschini** [comment]
This is now done. To follow up:

- The functions that have now been deprecated must later be removed from the public API (#454).
