### ISSUE TITLE
generic functions become app class methods

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#448]
This is a big rather philosophical issues. Are generic functions in Morepath really actually special static methods on the app class? This because the implicit parameter for a generic function is always the app's lookup anyway. If we installed generic functions as static methods on the app class this implicitness would go away.

To make this smooth we probably would need to adjust Reg to have an awareness of an actual app class.

@taschini what do you think?

**Comment by taschini** [comment]
Why static methods? If the implicit parameter for a *generic function* is always the app's lookup (which is effectively a class data member, via ``config``) that looks more like a class method.

Let's look at what ``morepath.App.set_implicit`` really does:

```
class App(dectate.App):
    ...
    def set_implicit(self):
        if _implicit_enabled:
            reg.implicit.lookup = self.lookup
```

Where ``reg.implicit`` is a ``threading.local`` object.  In fact, one could rewrite set_implicit to something like

```
class App(dectate.App):
    ...
    def set_implicit(self):
        if _implicit_enabled:
            morepath.current.app = self
```

where ``morepath.current`` is a ``threading.local`` object.  Perhaps ``set_implicit`` could be better called ``set_current_app`` or something like that.  So instead of having something like

``` 
morepath.forget_identity(response)
```

which is equivalent to

```
morepath.forget_identity(response, lookup=reg.implicit.lookup)
```

you would have

```
app.forget_identity(response)
```

in those cases where access to the current app is available in the current lexical scope, or

```
morepath.current.app.forget_identity(response)
```

in those case where you don't have direct lexical access.

This does not exclude the need for *real* generic functions.  If you come up with  some functionality in an extension outside of ``morepath`` core you cannot simply add a method (instance or class may that be), but you would still need to have dispatch on the app class.

**Comment by faassen** [comment]
I figured static methods as they just plain dispatch on the class of the app, and that's enough -- the function itself does not need access to the class object as an argument. 

I'm not sure you'd still need generic functions. If we had way to add a static method to the class (that do predicate dispatch on its arguments), either doing it in a subclass or using a directive, that would be sufficient for the use cases of extensions too, right?

The one thing I'm slightly concerned about is namespacing: the namespace for directives would become the same namespace as the namespace for the generic app methods, and that's already shared with the namespace for any application parameters or custom functionality. Right now the namespace for generic functions and directives is separate.

This proposal is quite radical. Reg would change to be app-class aware, and all generic functions are methods. Implicit apps/lookups go away entirely. You can still use Reg to implement plain generic functions, but that'd be a matter of binding the generic function of a class to a module, and it wouldn't dispatch on the class at all anymore.

**Comment by faassen** [comment]
This *would* imply that you'd need access to an app object to call a dispatch method at all. I think in the Morepath core this is always the case as we always explicitly pass the lookup anyway. We don't have many extensions that use the function directive yet, so I think we are probably safe there. The services pattern @blaflamme introduced does use the function directive but it already needs the app for other reasons, so the modification looks simple enough.

**Comment by faassen** [comment]
Would appreciate your input too, @href and @henri-hulski 

Effectively in practice this would mean that ``morepath.generic`` would go away and what's in there would become special methods on ``morepath.App``, so you'd see things like:

```
class App(dectate.App):
    @reg.dispatch(reg.match_class('model', lambda model: model))
    def class_path(model, variables):
          return None
```

``@reg.dispatch`` would also imply ``@staticmethod``.

and an adjusted way to register functions so that you register concrete implementations for ``App.class_path`` instead of ``generic.class_path``.

Having to pass around lookup parameters, implicit or explicit, goes away in Reg, which probably results in a mild performance increase in Reg.

**Comment by faassen** [comment]
See also #446 for a concrete step.

**Comment by faassen** [comment]
An alternative is to use predicate dispatch itself to switch to the right app class. The functions would stay plain generic functions, but they'd all get a hidden (?) first ``cls`` argument. Invocation would still need to involve the app class or instance in some way. So I am inclined to think ``@staticmethod`` is a better fit as it does what we want already. It also probably has somewhat better performance characteristics.

**Comment by href** [comment]
I'm not quite sure I see the benefit of this change yet. Is it a pure organisational improvement?

Also, wouldn't the static 'settings' function conflict with the settings property on the app, to name an example?

**Comment by faassen** [comment]
The basic idea is that explicit is better than implicit.  We currently have an implicit global lookup (more or less the app class). This is passed into any generic function call if no explicit lookup is supplied.

The Morepath core always passes an explicit lookup. But extensions that use dispatch functions don't.

I realized that instead we can make the generic functions static methods on the class. This is more Pythonic than passing along a lookup argument everywhere. It also should be faster.

Your point concerning settings is a good one. We need a reg option to make a property to support that.

**Comment by taschini** [comment]
I think that in the specific case of ``settings``, the property is all you need.

**Comment by henri-hulski** [comment]
👍 I like it. It makes things more straight forward. Never was a big fan of the lookup pattern as it's not so easy to reason about. 
And `app.users_service()` for getting a service is really cool. 
Just curious what effect this will have on settings.

**Comment by taschini** [comment]
@henri-hulski see my last commit in [more.jwtauth](https://github.com/morepath/more.jwtauth/commit/a6ae68fedae4d627ac8a37f30c3836e680238fc3).

**Comment by henri-hulski** [comment]
@taschini Yeah that was exactly what I'm talking about. Looks much better now.

**Comment by faassen** [comment]
What do people think about the namespace issue? App will get a lot more methods on its class. I imagine they should be private (underscore prefix) by default otherwise we make public all generic functions.

**Comment by href** [comment]
> What do people think about the namespace issue? App will get a lot more methods on its class. I imagine they should be private (underscore prefix) by default otherwise we make public all generic functions.

I do think this is an important issue. Ideally they would be stored in a class variable like `app.generic` i.e. `app.generic.settings`. Though that would bring us back to the explicit lookup, unless `generic` *is* the lookup (if that makes sense).

**Comment by faassen** [comment]
Yeah, I'd be tempted to stuff it on a sub-component like you suggested, but doing that breaks one important reason we'd use staticmethod in the first place: subclassing expectations.

We could alternatively separate the application object from what gets mounted so that you are free to pick things in the object you mount.. Not sure what that would look like.

**Comment by faassen** [comment]
I've done some experiments yesterday to see whether I could tweak Reg to do this. It can be done without huge changes. There are a few difficult bits:

* it will have to be class methods, and class methods need a first (``cls``) parameter. But the functions we plug in don't have such a ``cls`` parameter. We need to make it so that you can plug in functions without ``cls``. Right now there's also some signature checking code that's interfering,
as the functions we plug in don't have ``cls`` whereas the generic method does.

* the order of decorators looks like this in my experimental code:

   ```
   class MyApp(morepath.App):
       @classmethod
       @reg.dispatch()
       def method(cls, foo):
            ....
   ```

  This order is required as ``@reg.dispatch`` needs access to the underlying method object.
  I think ``@reg.dispatch`` needs to gain the ability to do ``@classmethod`` too to save
  some typing.

* the notion of a lookup goes away and is replaced by just calling the generic methods on the
  app instance. In fact this does use a lookup object internally stored on the app class. We need
  to change Morepath's initialization code in some way to make sure that this lookup is present
  and autocommitted, plus installs the correct caching logic.

Besides this a lot of work needs to go into adjusting the docs and the tests in Reg.

**Comment by faassen** [comment]
I've also done some analysis on how "lookup" is used in Morepath, and how generic methods would need to change if they're placed on the app class.

* currently lookup is manipulated explicitly within traversal in ``publish.py``, deferred link resolving,
  and ``request.view``. We also already need to change app. We can eliminate the lookup 
  manipulation here as manipulating the app is enough.

* ``app.settings`` is a property. This implies that Reg needs the facility to install generic class 
  *properties* dispatch logic along with plain class methods. I'm not sure whether that's possible, but
  a workaround where the property is created above a generic class method is easy.

* ``generic.path_variables`` in its default implementation falls back to ``generic.default_class_variables``, and to do this it needs access to the lookup. In the new setup it needs to have access to the cls argument instead to enable this.

Some generic methods can easily become class methods:

* ``generic.class_path`` can just become ``_get_class_path`` which uses that already.

* ``generic.remember_identity`` and ``generic.forget_identity`` can also be directly implemented
  using Reg again.

There are conflicts with directive names:

* ``generic.view`` conflicts with the ``view`` directive.

* ``generic.verify_identity``

* ``generic.load_json`` 

* ``generic.dump_json``

* ``generic.link_prefix``

In general we probably need to make most of these private anyway and prefix them with ``_``, because they don't belong in the public API (they're not there now). This does mean that ``generic.view`` becomes the more ugly ``app._view`` or ``app._get_view``.

**Comment by taschini** [comment]
Let's take into consideration the triplet ``forget_identity``, ``remember_identity`` and ``identify``. What they do is to delegate the implementation to an ``IdentityPolicy`` object.  It seems to me that you don't really need any special machinery to do that.

As an experiment, in #463 I removed ``generic.identify`` entirely and the code does not seem really much worse for it.  I'm not sure what kind of advantage would you get by having ``reg`` attach an extra static/class method to ``App`` to implement that kind of delegation.

Am I missing something?

**Comment by faassen** [comment]
Thanks for doing this experiment! I do think you're missing something, as none of the identity policy functions actually dispatch based on their arguments. But this is interesting in itself (see below!).

But you can't do this for something like `permits` or `view` which dispatch based on aspects of their arguments. You have to use Reg to make that work.

So perhaps we should introduce the following approach: if a function doesn't dispatch on its arguments, we use the simple method call on their registry, instead of using the generic function story. This takes care of a lot of things in ``morepath.generic`` and makes things simpler. But if it does dispatch on its argument, we should add these functions to the application object.

**Comment by taschini** [comment]
I see. We have 15 generic functions defined in ``morepath.generic``. Out of these, 

* ``settings``
* ``identify``
* ``remember_identity``
* ``forget_identity``
* ``load_json``
* ``link_prefix``

do not actually dispatch on their arguments, and I agree that we can we use the simple method call on their registry. Given that ``settings``, ``remember_identity``, and ``forget_identity`` are part of the API and they're scheduled for withdrawing to 0.16, I'll see whether I can implement the removal of ``load_json`` and ``link_prefix`` in #463, similarly to what I did for ``identify``.


The remaining nine functions in ``morepath.generic`` do dispatch on their arguments:

```python
@reg.dispatch(reg.match_class('model', lambda model: model))
def class_path(model, variables):
    …

@reg.dispatch('obj')
def path_variables(obj, lookup):
    …

@reg.dispatch('obj')
def default_path_variables(obj):
    …

@reg.dispatch('obj')
def deferred_link_app(mounted, obj):
    …

@reg.dispatch(reg.match_class('model', lambda model: model))
def deferred_class_link_app(mounted, model, variables):
    …

@reg.dispatch_external_predicates()
def view(obj, request):
    …

@reg.dispatch('identity')
def verify_identity(identity):
    …

@reg.dispatch('identity', 'obj', reg.match_class('permission', lambda permission: permission))

def permits(identity, obj, permission):
    …

@reg.dispatch('obj')
def dump_json(request, obj):
    …
```

I noticed that in the test suite there are no examples of ``verify_identity`` actually dispatching on the identity. Would it be possible for you to add a test for that?

**Comment by faassen** [comment]
I'll add an issue, I don't know when I'll get around to it. The idea is that you could have different kinds of identities in an app modeled with a different class that get verified in different ways as well.

**Comment by faassen** [comment]
Note that while ``settings`` becomes ``settings_registry`` and ``identify``, ``remember_identity`` and ``forget_identity`` are all methods on the identity policy, ``load_json`` and ``link_prefix`` don't exist on a registry right now. So to rewrite them to simpler method calls would require us to create such registries first.

**Comment by taschini** [comment]
You're right, of course.  I started playing around with ``link_prefix`` and realized that.  I'm still exploring possible alternatives.

**Comment by faassen** [comment]
Okay, I've made progress on this. On the ``dispatchmethods`` branch there is a version of Morepath that uses a new Reg that implements dispatch methods. What was in ``generic`` has moved either onto methods on the ``App`` class, or in the case of the ``PathRegistry``, into some methods of the path registry. Some things like ``remember`` and ``forget`` are now directly exposed dispatch methods, though mostly it's implementation and thus private -- as they were in ``generic``.

Besides ``generic.py`` also gone is ``implicit``, as we can be explicit throughout now.

Overall I think the branch cleans up the logic quite a bit. A lot of the ``lookup=lookup`` stuff is gone, replaced with simpler (and more efficient) method calls. Some complex lookup and implicit lookup management code is gone in publication and ``request.view``. But there is one design issue which I'll discuss in the next topic.

**Comment by faassen** [comment]
Currently if you want to write a generic function that needs to call *other* generic functions you declare a ``lookup`` argument in your function and you can pass this along to your other generic function calls. Instead you could also rely on the global implicit lookup and not deal with the ``lookup`` at all, at the cost of making testing more complex.

In the new approach this won't work anymore. Instead in Reg you can register a dispatch *method* instead of a function call. The first argument is the class or instance on which the lookup was performed, so in Morepath typically the app instance.

But for compatibility I provided ``register_function``, which wraps a simple function into a method that takes a first argument and then just ignores it, and then registers this method wrapper. A bit less efficient and I also ran into some issues with some assumptions that I've worked around by making the original function (obj) that was registered as the ``value`` attribute.

Morepath uses ``register_function``, not ``register_method``. But that means you *cannot* actually access the app anymore to call generic code, unless you happen to have the ``request`` lying around.

We arrive at a very similar issue to the one spelled out in https://github.com/morepath/morepath/issues/472 

There the problem originated because settings needs to be accessed, this is simply a broader issue of the same nature.

We may be able solve the problem by doing function introspection. If the *first* argument of a function being registered is ``app``, we use Reg's ``register_method``. If the first argument is something else, we continue to use ``register_function``.

There is still an issue. To avoid a circular import dependency I moved some dispatch methods from ``App`` onto ``PathRegistry``, but the first argument of *those* functions will be an instance of ``PathRegistry ``instead of of ``App``. So I think I need to resolve this circular import in another way and move them back.

Thoughts?

**Comment by taschini** [comment]
I have to say I'm still struggling with the idea that Reg attempts to do two things at once: 1) multiple dispatch, and 2) pluggability.

So I'd like to go back to our old friends ``generic.identify``, ``generic.load_json``, and ``generic.link_prefix``, the three "generic" functions that do not actually dispatch on their arguments. For these three Reg is obviously not needed for multiple dispatch, but is it needed for their pluggability? Not really (see #476): You don't need a ``RegRegistry`` for them, a plain object to store them is enough.

In fact, even at this stage I'd like to merge #476: beside simplifying the codebase, I think it will also help clarify the actual requirements for Reg.

On a side note, these three functions receive a request object as argument, so they are not affected by anything like #472.

**Comment by faassen** [comment]
Please hold off on the merge as it will make my merge harder. I think it is good that all dispatch methods behave consistently, including behavior with app argument, even if they take the request. This is one reason to avoid treating them differently. I will review Reg to see whether an additional shortcut can be taken if a method does not actually dispatch and contrast it with a non Reg approach.

**Comment by taschini** [comment]
> Please hold off on the merge as it will make my merge harder.

Of course I'll hold off, but I don't see how it will make your merge harder.  You just have to take away these three from the redesign.

> I think it is good that all dispatch methods behave consistently, including behavior with app argument, even if they take the request.

Let me repeat again the obvious: these three functions do not dispatch on anything so they don't need to be managed by Reg (they shouldn't have been defined as generic functions to start with).  Of course we can modify the signature and have them accept the app (but, honestly, I don't think that's a good idea), but there is nothing to be gained by Reg managing them.

On as similar topic I see that you brought back ``forget_identity`` and ``remember_identity`` to be managed by Reg. They already have a perfectly fine implementation that delegates them to the corresponding methods of the the registered ``IdentityPolicy``.  No need to bury that simple delegation under Reg.

Don't insist on ``forget_identity``, ``remember_identity``, ``identity``, ``load_json``, ``link_prefix``. Let them go, let them join ``generic.settings`` in the realm of the functions that once were "generic".

**Comment by faassen** [comment]
I wanted the refactor to be clear so I brought back forget_identity and friends, but I just now modified them again. While the implementations of the methods themselves is in fact more involved because I need to manually do fallback logic now, the registration logic is a huge amount simpler so it's worth it. (I think I simplified it beyond what was left in your version)

**Comment by faassen** [comment]
I'd like the directives to be as consistent as possible. I think we can get close with the "app as first argument" rule, though there are a few exceptions. I've done some analysis of the situation to come up with a plan for the various directives.

[analysis.txt](https://github.com/morepath/morepath/files/393695/analysis.txt)

**Comment by faassen** [comment]
I just compared Morepath dev version with the dispatchmethods Reg with Morepath 0.15, using https://github.com/faassen/welcome-bench

Here are the results (my desktop, Python 2.7):

```
                                 ms     rps  tcalls   funcs
morepath 0.15                  7683   13016     135      97
morepath dispatchmethods       6795   14716     128      91
```

So the dispatchmethods branch is faster by about 1700 requests per second. That's a pretty good speed boost. It doesn't affect the ranking compared to other web frameworks on this (silly) benchmark; Morepath is more than twice as fast at this than Flask, it's a lot faster than Django, it's still way slower than Pyramid, let alone Bottle or Falcon. There's a correlation between tcalls and and the time it takes per request, so this isn't a surprise.

The dispatchmethod approach cuts down on the amount of function calls by a bit, and the amount of different functions in use also goes down. So this change is good from a performance perspective. Since less functions are involved it may also make the code more readable/debuggable, but that's harder to measure.

It's possible that the "app as first argument" changes we have yet to make have a performance impact, but I expect that impact to be neutral or even positive as if you do use it, Morepath won't have to generate a wrapper function that gets rid of the app argument.

**Comment by faassen** [comment]
I still have these things going through Reg which strictly don't have to:

*   load_json

*    link_prefix

These could now be implemented by simply setting the function given by the directive on the App class that directive is invoked on, i.e in perform something like:

```
app_class.link_prefix = obj
```

There are two problems:

* the app class is not easily available. We should add a feature to Dectate to make this available somehow.

* ``obj`` doesn't have a first ``self`` (or ``app``) argument. We need to install a wrapper that discards this first argument if it does not.

**Comment by faassen** [comment]
Is it possible to also treat the identity policy methods this way, directly setting them as methods on the app class? I think so, though it'd be somewhat odd to take a bound method from the identity policy and then bind it again as a method to the App class.

**Comment by faassen** [comment]
See https://github.com/morepath/dectate/issues/4 for the dectate issue.

**Comment by faassen** [comment]
Even though the dispatch_methods_decoupling branch isn't entirely done yet (there are cleanup issues with multiple commits), there's enough to show the performance is about the same as the dispatch_methods branch:

```
                ms     rps  tcalls  funcs
morepath      6840   14621     128     92
```

The total amount of calls is in fact identical to the dispatchmethods branch (which takes a lookup from the app class). I think this is because in the end they use descriptor and go through a very similar cache too. Even though Reg itself is "flatter" this doesn't really come out in the benchmark because the registry of predicate registries in Reg isn't hit during runtime because Reg covers it with a cache. The performance gains are from the removal of the "lookup" argument extraction and passing and replacing it with method calls, not the dispatch performance itself.

I suspect that some measures taken on this banch will have a better real-world performance  - in particular various authentication related methods and link prefix aren't going through Reg at all and are simply methods directly installed onto the App class, which should make that code path faster. But that's not really exercised by this simple benchmark app. And those measures are not unique to this branch or approach and could (now that we have the app_class_arg feature in Dectate) be easily applied to master as well.

**Comment by faassen** [comment]
Here is a comparison of the code of the dispatchmethods branch A) versus dispatchmethods-decoupling (B). The first uses the dispatchmethods branch of Reg, which makes it entirely method based. Each method wants to access the 'lookup' attribute on the app class. The second uses a simpler flatter Reg which keeps the registry with the dispatch function directly, instead of having a registry of predicate registries. These dispatch functions can also be installed as methods.

In A, there is still a ``lookup`` method on the app class like in master, in B this is gone. This lookup method in A also does a commit. Both branches also do a commit in the construction of the publish method. The removal in B has the consequence that the tests that *do not* go through the web client (and thus does not create publish) fail because they lack an explicit commit and the implicit one isn't triggered anymore. I've adjusted the tests to trigger an explicit commit in those cases.

The way the identity policy functions is accessed has been simplified in B, along with link_prefix and such. These are simply installed as methods on the App class during configuration time. This required a modification in Dectate. Now that this modification is there we can in fact modify A (or master) to do the same thing, so this is not a real difference. In B the identity policy registry is also gone as a consequence, but this coudl also be removed in A and master.

There are various dispatch methods like ``_deferred_link_app`` that take ``app`` as an explicit first argument. In B I've adjusted this so that they are installed as methods, meaning that the ``app`` argument does not need to be passed in explicitly anymore. I suspect I can make the same modification in A, but I haven't done so yet.

In A there is a single caching lookup created, in B each dispatch method refers to its own caching lookup. B is slightly more verbose. What has the best real-world performance consequences in unclear -- there may be some benefit to B having separate LRU caches per method, but it may also result in more memory use.

 In A the ``reg_registry`` is part of the configuration of many directives. In B this is gone, instead the registration happens directly on the methods. Care needs to be taken in B to register on the method of the actual class being configured. To this end various directives and registries now need access to ``app_class``.

In B, registrations do not exist in ``App.config`` anymore for dispatch functions, instead they are in the functions themselves. This means that in B the responsibility for cleaning has moved to Morepath; there's a new clean method in ``App`` (``GenericApp``) that does so, that uses a new Reg helper, ``clean_dispatch_methods``. Dectate has been modified so that this method is called before each commit. In A all configuration is strictly in ``App.config`` and this is already cleaned out by Dectate, so this extra work is not needed.

In B, Reg has been simplified so that dispatch_external_predicates is gone in favor of a ``add_predicates`` method on the dispatch function or method. This makes interaction in the predicate installation story much cleaner than on A or master. 

While the predicate  part of the function directive is much simpler in B,  B's function directive is more complex in its actual registration part to make sure it registers for the right class, it needs to go and do ``getattr(app_class, self.func.wrapped_func.__name__)``, i.e. get the name of the dispatch method referenced and get it again from the class in order to register against it properly. 

This modification also has a minor impact on simpler registrations such as on ``app_class._permits`` instead of on ``reg_registry.register_functionApp._permits)``, again ``app_class`` has become an argument instead of ``reg_registry``. In general the registrations in B are a bit shorter, though not by much.

B already implements the rule that if you specify the ``app`` argument as the first argument, it is passed in (and no wrapper function is made), through ``register_auto``. See the analysis I did in an earlier comment. I have prototype work for A that does the same. This reminds me I should write tests for B that demonstrate its correct behavior in all cases -- I also wonder whether I should modify the way views work so that the app argument is optionally passed.

I've already previously comment that A and B have very similar performance characteristics for "hello world" -- both are faster than master in the same way.

Overall the two approaches, A or B, aren't that different. In B you need to remember to use app_class for the proper registration (instead of reg registry),  there's a bit of added cleanup complexity (but now that's been automated), you need to do a few more explicit commits in tests, and predicate registration is simpler. For B, Reg is also simpler as its main Registry is gone, and predicates are simpler to add, though there's some new added dispatch method magic. A is slightly closer to Morepath as it is today, and its Reg is less magical, but descriptor magic does get added there too.

**Comment by faassen** [comment]
I've added tests to B to enable various functions with an optional first app argument:

* ``permission_rule``

* ``verify_identity``

* ``dump_json``

* ``load_json``

* ``link_prefix``

* ``variables`` function passed to the ``path`` directive.

These already took an app argument as the first argument and are simply registered as methods now, which simplifies their calling sites:

* ``defer_links``

* ``defer_class_links``

I would like to adjust the various ``template_`` directives but their functions get called early on in the process, which helps performance. So doing this would involve quite involved refactorings which I'll defer to the future -- if we can tolerate not having access to the settings here. Can we?

In the analysis ``identity_policy`` is also suggested to get an app argument. Adding an ``app`` argument to the *methods* of the identity policy would seem possible but currently breaks on some detail of the way methods get bound to the App class -- I've added an xfail test. I wonder whether identity policy as a class isn't against the general idea of Morepath, and whether we shouldn't pull it apart into an identity, remember and forget directives. But that's another discussion.

I will now take a look at the view directive, as it's more involved.

**Comment by faassen** [comment]
I took a look at the view directive, but I think a modification to move parts of the View class to the publisher makes things a bit more complex, due to the juggling of the view function versus the view component versus the view method. I will leave things as is for now.

**Comment by faassen** [comment]
This is @taschini's pull request, with comments there: https://github.com/morepath/morepath/pull/482

**Comment by faassen** [comment]
For a performance comparison here is @taschini's branch:

```
                ms     rps  tcalls  funcs
morepath      9821   10182     204    108
```

A lot slower, because @taschini's branch doesn't implement caching yet. Otherwise it will probably be about the same as my branches get.

**Comment by faassen** [comment]
I made a small tweak to my decoupled branch to forgo a wrapper when view is invoked:

```
                ms     rps  tcalls  funcs
morepath      6768   14775     127     91
```

The performance is about the same, but the amount of function calls (and uses) has gone down by 1 as expected.

**Comment by faassen** [comment]
I've fixed the issue with adding methods to the app class from the identity policy, at the cost of a function wrapper to make it work on all Pythons.

I also rebased my branch off master.

**Comment by faassen** [comment]
Today I realized that I could rip another layer of indirection from Reg, resulting in the following benchmark results:

```
                ms     rps  tcalls  funcs
morepath      6715   14892     126     90
```

The performance is almost the same, but there's one function less called.

**Comment by faassen** [comment]
And again I got rid of a minor indirection in Reg that wasn't necessary:

```
                ms     rps  tcalls  funcs
morepath      6707   14909     125     89
```

While again it doesn't do much for the benchmark here, it should help someone debugging through Reg a little bit again.

**Comment by faassen** [comment]
An experimental C version of argextract gives me this:

```
                ms     rps  tcalls  funcs
morepath      6520   15337     119     88
```

Only a small increase. Dispatch call performance isn't radically increased by this, unfortunately. ``dispatch.__call__`` looks like it could be reasonably easily translated to C, but some of the calls it makes would need to remain in Python, so as a performance boost it may not be worth it; it's possible it helps people debugging through it.

**Comment by faassen** [comment]
After discussing it with @taschini I've reverted the code that makes an optional app argument exist for the identity policy methods that get installed; these would behave rather unusually for Python methods, and you can already get to the app here through request anyway.

**Comment by faassen** [comment]
With @taschini's change to Reg's dispatch logic we get:

```
                ms     rps  tcalls  funcs
morepath      6402   15619     117     86
```

I tweaked parameter factory generation on Morepath too to avoid doing work when there are no parameters expected, which helps the benchmark a lot:

```
                ms     rps  tcalls  funcs
morepath      5456   18330     106     80
```

**Comment by faassen** [comment]
This has landed, so closing this issue. Eventually I'll create a performance issue somewhere. Thanks @taschini who inspired all these changes!
