### ISSUE TITLE
Settings access in permission_rule

### ISSUE THREAD

**Issue by href** [morepath/morepath#472]
With the upcoming removal of global settings access it becomes impossible to access the settings from a permission_rule. This however can be useful if you want the settings to have an influence over the permission rules.

For example:

```python
from morepath import settings

class Public(object):
    pass

class Private(object):
    pass

@App.setting_section(section="roles")
def get_roles_setting():
    return {
        'logged_in': {Public, Private},
        'anonymous': {Public}
    }

@App.permission_rule(model=object, permission=object, identity=None)
def has_permission_not_logged_in(identity, model, permission):
    return permission in settings().roles.anonymous

@App.permission_rule(model=object, permission=object)
def has_permission_logged_in(identity, model, permission):
    assert hasattr(identity, 'role'), """
        the identity needs to implement a role property
    """

    return permission in settings().roles.logged_in
```

Here definition of what a role can do is done via settings, while the role itself is defined on the identity. So we can either change the role of a user or change the roles in a child application.

The child application part is crucial, so if we somehow had this information on the app *class*, we would have to be sure that it accounts for child applications overriding those values.

**Comment by taschini** [comment]
See also 

https://github.com/OneGov/onegov.core/blob/master/onegov/core/security/roles.py
https://github.com/OneGov/onegov.core/blob/master/onegov/core/security/rules.py

**Comment by faassen** [comment]
Okay, this is a problem; I had hoped we'd have access to the app in all places needed but apparently we don't.

The question is how we go to solve it. We have some directives that pass the app in, or take the request (which has access to app). We have other directives that don't pass the app in, but where it's useful to have the app to do stuff with settings (or access methods on apps, i.e. services with the new Reg). Do we have any directives where we *shouldn't* have access to the app?

We could solve it on an ad-hoc basis and pass in the app in addition to the rest into ``permission_rule`` and other directives that need it. But there are some problems with it:

* it's a bit ugly in that it's inconsistent -- app is passed in as what argument where?

* how do we ensure backward compatibility? we don't want directives that don't take app as an argument to break. We could do this with ``reg.mapply`` but there's a performance cost. We could also add a configuration knob to the directive that's ``False`` by default but if ``True`` it also passes in the app. That would be configurable but it also has a performance impact. Another ad-hoc solution would be to stamp the request or app on identity or the permission but that seems ugly and bug-prone.

I don't want to introduce a global app instance to solve it -- that's what we had with the implicit lookup and is what we're trying to get rid of.

Can someone produce a list of all directives where we really don't have access to app (not through request or another object either)?

Anyone has an idea on how to solve this, either in an ad-hoc or general way?

**Comment by taschini** [comment]
In the worst case we know that the ``visit_app`` proposed in #467 solves this kind of problems.

**Comment by href** [comment]
I'm not sure it's an exhaustive list, as I looked at the code and the docs. So I could be missing something, but these seem to be the directives that have no settings access in the future:

* converter
* link_prefix
* permission_rule
* predicate
* predicate_fallback
* template_directory
* template_render
* verify_identity

Arguably, `verify_identity` would have to get the same treatment as `permission_rule`. In general I would say it's always useful to have settings access.

**Comment by faassen** [comment]
@taschini could you explain how ``visit_app`` solves any more problems than the current implicit lookup system? Would it be writing the current app to a global? That's something I'd really like to avoid; if we get rid of the implicit lookup global we shouldn't replace it with an implicit global app.

**Comment by taschini** [comment]
Let's start with an observation: the current ``reg.implicit.lookup`` is no longer needed in 0.16. Currently it is only needed by ``morepath.App.function`` decorated generic functions, and the Reg redesign should take care of that.

So ``morepath.Request.visit_app`` is a hook whose default implementation is NOP:

```
def visit_app(self, app):
    pass
```

Now most web app developers will be fine with that, but some, like Denis, need something more.

So they can have a global thread-local object (let's call it ``current``) and the following request class:

```
class AppTrackingRequest(morepath.Request):
    def visit_app(self, app):
        super(AppTrackingRequest, self).visit_app(app)
        current.app = app
```

which can be used with their app:

```
class app(morepath.App):
        request_class = AppTrackingRequest
```

What's the advantage of this solution?  There is no global state within Morepath.  But if your project requires one you can have that. ``visit_app`` makes that possible. It's not Morepath (or one of its dependencies) that has a global state: it is your project that has a global state.

Having said that, it might be the case that in this situation there is a way to avoid a global state, and we definitely should look for that possibility.  But if there is no way to avoid it, then ``visit_app`` allows you to have it.

**Comment by faassen** [comment]
Okay, so ``visit_app`` provides pluggable global state, whereas currently Morepath always has global state. I can see that as an advantage, though there's also the disadvantage that the pluggability means there's no universal way to do global state, like there is with the implicit lookup now. If you want to write frameworky apps that rely on settings that doesn't feel particularly good.

It'd be better if we could do away with global state altogether -- spending work to get rid of it in one place only to have it pop up in another just doesn't feel right. I'd rather break a lot of directives by passing the app in than that, but I hope we can avoid that too somehow.

One way to go about it looking at @href's list is to pass in request into all of them, and make a rule that any directive that gets executed during the request can take request. ``path`` is already like that but it uses ``mapply`` and ``mapply`` has a performance impact.

Perhaps we can do it without ``mapply`` but with function argument introspection during registration time. If a ``request`` argument is there, we just register the function directly. If it's not declared we create a small wrapper function that does take the request argument and then discards it. That has some performance impact but it's not huge. We could then make it a general rule that you can declare the ``request`` argument in a directive if you need access to the request or app.

**Comment by taschini** [comment]
> Perhaps we can do it without mapply but with function argument introspection during registration time. If a request argument is there, we just register the function directly.  If it's not declared we create a small wrapper function that does take the request argument and then discards it.

This is surely possible (see the PR above). I pass the app instance instead of the request instance but the mechanism is exactly the same.

**Comment by faassen** [comment]
I missed this PR, but I converged on something very similar in issue #448 earlier. So that's confirmation this seems like a good idea. I want to solve this generally for dispatch methods, and pluggable methods, so that we have universal access to app as the first argument if we use it. It is in fact slightly *faster* to declare app as the first argument with the new Reg as no wrapper function is needed.

**Comment by faassen** [comment]
Oops, wrong button, issue still open.

**Comment by faassen** [comment]
This has now landed. If ``permission_rule`` has a first argument that's called ``app``, that will be the app instance.
