### ISSUE TITLE
Simple sapmle gives 404 error...whats wrong?

### ISSUE THREAD

**Issue by catroot** [morepath/morepath#477]
Hi there!
It seems to be a bug or some improvements needed.

The sample app:
```python
import morepath

class App(morepath.App):
    pass

class Model():
    pass

@App.path(path="/", model=Model)
def main_index():
    print("main index invoked")
    return Model # or whatever?

@App.view(model=Model)
def show_index(self, request):
    print("View index invoked")
    return "View index" # Didn`t get hit. (((


morepath.run(App(), host="0.0.0.0", port=5001)
```

Whis should work, but doesn't, returning 404 error.
For my suggestion, if i pass model=Model to App.path decorator - decorated function should be defined inside model class and therefore recieve class instance as a first argument, which should be `self`. 
And what for they must return a class, that is out of function scope (or even global)? 
Instead of this, `App.path` decoradet function must be defined inside of the `Model` class to contain useful things for those paths views (for example, inderaction with methods from other controllers) or be empty at all.

So, there must be a way to define several views for the model with different paths. If we want to build some more complex app, we need to get out of one_model->one_view paradigm. 
If morepath will deliver ability to choose a view from controller - it will be nice.

These issues minifies morepath scalability to the floor (at last in my case).

**Comment by faassen** [comment]
The path directive should return an instance of Model, not the class itself.

You can have only one path per model class to have one canonical link for a model. What is your usecase for more than one link per model class?

Note that you can mount other independent apps, each of which can declare a separate path for the same model class.

**Comment by faassen** [comment]
Note also that you can name views, one could be the default empty string, another 'edit' or whatever you want. The view name is appended to the path.

**Comment by catroot** [comment]
You are right, this works:
```python
@App.path(path="/", model=Model)
def main_index():
    print("main index invoked")
    return Model()
```
But the point is to return something related to class or function, what for returning something out of function scope? Why not to return instance of the Model from decorator? I suggest to attach an `App.path` decorated function to the model passed to decorator.
1. there will be no need to return a model instance
2. we can use returned value to determine a model view to use for render
3. if we pass the request to App.path decorator (why not? controller may need this info), then we can call a view decorated model function explicitly via self, respecting their decorated attributes and return their response.

There will be even more path to handle models and views through controllers

If a model a little bit complex and url contains an arguments, a model may need a dozen of views.
I.e. the same data can be represented in many ways: a list, kanban, calendar or something else.
There are no need to have several models and even different url paths.
For some cases, there might be better to show a login screen in case of not authorized request when auth expires, instead of throwing 403 error and not redirecting to login url.
On a single model a whole application can be written, with many controllers and views.

Morepath is better than lessways, right?

**Comment by faassen** [comment]
Normally a model instance is instantiated with some data or you get it from a database, etc
 But the path decorator can already be applied to the model class if that is sufficient.

I recommend against building a large application against a single model class. It is better in this case to consider several more specialized models.

The path function (not the decorator) can take additional arguments that are URL parameters. You can also declare a request argument and access that.

Nonetheless I recommend keeping the request out of the model instances. Models should have no knowledge of the web. Extract all you want from the request and only then pass it into the model.

**Comment by faassen** [comment]
Note that you can create a custom view for the 403 error and redirect to a login path.

**Comment by catroot** [comment]
>The path function (not the decorator) can take additional arguments that are URL parameters. You can also declare a request argument and access that.

Is there a some example for this case?

**Comment by faassen** [comment]
http://morepath.readthedocs.io/en/latest/paths_and_linking.html#url-query-parameters

http://morepath.readthedocs.io/en/latest/api.html#morepath.App.path

http://morepath.readthedocs.io/en/latest/views.html#exception-views

http://morepath.readthedocs.io/en/latest/api.html#morepath.redirect

**Comment by faassen** [comment]
I recommend against using absorb for paths unless you really want to catch all subpaths, for instance to pass it to a single page frontend with client side routing. If you do not have such a specific use case do not use absorb.

If you declare an absorb argument it passes what got absorbed. http://morepath.readthedocs.io/en/latest/api.html#morepath.App.path

**Comment by catroot** [comment]
Thank you for pointing me to what i missed.

Nevertheless, i vote to improve App.path decorator to pass decorated function into model class, as if it would be in case of wrapping a whole class.
And, also count my vote for remove the need to return an instance of model from decorated function. This can be done by decorator itself.

This will make things more transparent, predictable and also more pythonic and atomic.

**Comment by faassen** [comment]
I don't understand these proposals:

* Pass the decorated function into the model class as an argument during construction? Why?

* If you use the decorator on the class directly, there is no need to instantiate the class yourself.

In most cases you do however want to control what instance is returned from a path function and call some API to get the information to do so.

**Comment by catroot** [comment]
I'm used to determine the path for view, but not for a model and this causes me to get a little confusion with morepath logic.
For me is a much simplier to have complex models and controllers with simple views, which is not mapped to them in a hard way. Just take from view any controller you want and do what you need, then return what requested. Usual for me when models does't rely on views and vice versa. All work is done at controllers. Views just wraps them to render output.

But defining routes for models... without controllers... passing models to a view... single model=>single view... That's makes me stuck.

For now, i've got the point.
Unfortunately, morepath elasticy suits to limit me in the choice of my way. 
For such simple things, they can handle, i found morepath overcomplicated. 
No need in mountains for a mouse to born, imo.
