### ISSUE TITLE
coverage check a bit weird

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#483]
We have this automated coverage check thing. Just now I added a few tests to Reg explicitly to *increase* coverage, that was their own purpose, in particular here:

https://github.com/morepath/reg/pull/40#commits-pushed-6dd8032

The reaction of the coverage reporter is to say coverage *decreased* for that checkin, for instance:

``Coverage decreased (-1.04%) to 98.957% when pulling 681f34c on decoupling into feef060 on master.``

I saw this response too in a few earlier checkins where I removed unused methods -- that should *increase* coverage, not decrease it.

So what's up with this coverage reporter? It seems to respond very counterintuitively to checkins.

**Comment by henri-hulski** [comment]
There are 2 coverage tests. One is for the commit and the second for pulling the PR branch (in this case decoupling) into master. The second one shows the changes of the PR branch after the commit compared to master. 

Somehow the first isn't visible on the PR, but you can view it on coveralls.io.

Really irritating. For me coveralls is also to verbose. 

When I'm able to reach 100%, I just add to the coverage testenv in tox.ini a test if 100% is reached. Otherwise the test fails and shows missing line numbers:

```python 
[testenv:coverage]
basepython = python3.5
deps = {[testenv]deps}
commands =
    coverage run --source server -m py.test {posargs}
    coverage report -m --fail-under=100
```

**Comment by henri-hulski** [comment]
So if the coverage report shows that coverage decreased less than at the previous report it means that it actually increased.

**Comment by faassen** [comment]
@henri-hulski it's a bit heavy to maintain 100% coverage for Morepath, given multiple Python versions. I wouldn't want to break the build each time I broke 100% coverage -- I'm already irritated flake 8 failure breaks the build, though it does help me find issues.

But it is rather verbose and confusing. On the other hand it's useful to keep track of it...

**Comment by henri-hulski** [comment]
@faassen Coverage is only tested for Python 3.5.
But I'm agree that it's difficult to achieve for morepath.

**Comment by taschini** [comment]
Coverage is now 100.0%. As long as we manage to keep it at that level we won't have this kind of problems.

**Comment by henri-hulski** [comment]
So I think we can use `fail-under=100` and remove coveralls from Travis. 
If a PR goes beyond 100% in both cases either fails coveralls or the coverage test. 
So it's similar.

**Comment by faassen** [comment]
Let's go with this and then we'll see whether that is more workable.

**Comment by henri-hulski** [comment]
It's now implemented in Morepath and Reg. 
I think it's still missing in CHANGES.txt.

**Comment by henri-hulski** [comment]
Added changes. So this one is done.
