### ISSUE TITLE
move load_json, body_obj, body_model to an extension

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#514]
I added the ``load_json`` infrastructure years ago. The idea is to recognize on an application-level
what kind of JSON content is being posted, and convert it into a Python object. You can use this
application object with ``request.body_obj``. With ``body_model`` you can then write views that specifically match that kind model.

This however seems to be the wrong abstraction for typical REST applications. These applications know on a per view-basis what kind of body they accept. Dispatching on ``body_model`` isn't much of a use case.

Meanwhile I am in the process of adding a ``load`` hook to views, which is a simpler abstraction
that seems to do what people typically want: a simple reusable function you can plug into views
that helps deserialize and validate request body content.

I therefore want to move the load_json behavior into an extension in the next release. If you need the behavior you can subclass from the extension. I think this can be done without trouble -- I think we already have the right points to hook this into the core, but we'll see.

I think ``dump_json`` is still useful to reuse serialization behavior and can stay.

The package could be called ``more.body_model``.

Any volunteers?

**Comment by faassen** [comment]
So this would require creating a new app subclass in this new package.

You'd create a request subclass that defines the ``body_model`` property and set this to ``request_class`` on this app subclass.

You also need to move the ``load_json`` directive to this app.

You need to take the body_model predicate from core to this app.

You also need to move all the tests that deal with body_model into this package, and make sure that the tests for dump_json do stay in Morepath core, as we don't want to move this (in case the tests are woven together, but I doubt it).

Finally you need to change the documentation to remove references to body_model and load_json and move it to the README of the subpackage.

**Comment by faassen** [comment]
Once this has landed I want do a release of Morepath so I can release more.marshmallow.

**Comment by henri-hulski** [comment]
@faassen I just made a search in Github and Google and it seems that nobody uses load_json.
Maybe we can ask around here and in discord if someone uses it and if not just throw it out. 

I think sometimes it's good to make a little clean up.

**Comment by gmc444-b** [comment]
I've made use of load_json.

**Comment by faassen** [comment]
Could you describe a bit how you've used it?

Note that moving it to a separate extension shouldn't actually break anything (once you use the extension)

**Comment by faassen** [comment]
I thought about removing it entirely but realized it could be extracted as an extension without too much trouble.

(Though a mechanism to introduce methods and properties to request using a directive would be nice)

**Comment by henri-hulski** [comment]
@faassen I think for the next release in accordance with  our release policy we should depreciate it and remove or move it in the release after.

**Comment by henri-hulski** [comment]
So if we want to move it we should create more.body_model and depreciate body_model, body_obj and load_json and ask for switching to the extension. 

@faassen What you mean by 
> Though a mechanism to introduce methods and properties to request using a directive would be nice

**Comment by henri-hulski** [comment]
@faassen BTW we have already 0.17.

**Comment by gmc444-b** [comment]
I've been using load_json for services that don't conform to the normal REST model,  a decision which is unfortunately is out of my control. I'm okay with the functionality moving to an extension, but not with it's complete removal.

**Comment by henri-hulski** [comment]
@faassen I have looked into this. I think I'm not really able to depreciate as I never did this, but I successfully removed it from Morepath.
And moved it to more.body_model. Not so successful.
All tests are failing with 
```sh
infos = [<morepath.predicate.PredicateInfo object at 0x7f478c85f7b8>]
￼
 
    def toposorted(infos):
        """Sort infos topologically.
    
        Info object must have a ``key`` attribute, and ``before`` and ``after``
        attributes that returns a list of keys. You can use :class:`Info`.
        """
        key_to_info = {}
        depends = {}
        for info in infos:
            key_to_info[info.key] = info
            depends[info.key] = []
        for info in infos:
            for after in info.after:
>               after_info = key_to_info[after]
E               KeyError: <function request_method_predicate at 0x7f478cb77488>
 
../morepath/morepath/toposort.py:19: KeyError
```

I think I will make a PR on morepath and create more.body_model so you can have a look.

**Comment by henri-hulski** [comment]
@faassen I have made the PR on the `load` branch.
So if you are happy with the PR you can merge it into that branch and continue working on it or just merge it after together in master.

**Comment by henri-hulski** [comment]
Created [more.body_model](https://github.com/morepath/more.body_model).

**Comment by jugmac00** [comment]
I think this can be safely closed now.
