### ISSUE TITLE
link_prefix does not work as expected

### ISSUE THREAD

**Issue by inytar** [morepath/morepath#516]
As mentioned on discord link_prefix does not do work as expected. Using the code in this gist: https://gist.github.com/inytar/5cb0b7b4d192e22f83180ff99a2cc8be I expect to see:
```
{
"external_link_def": "http://external.com/external",
"external_link_expl": "http://external.com/external",
"internal_link": "http://127.0.0.1:5000/"
}
```
but get:
```
{
"external_link_def": "http://127.0.0.1:5000/external",
"external_link_expl": "http://127.0.0.1:5000/external",
"internal_link": "http://127.0.0.1:5000/"
}
```
I'm using morepath 0.17 on Python 3.5.

Some more experimenting shows that only the root App's link_prefix is used.

(As a discussion point: what should you expect when mounting an app on an other app? Use the link_prefix of the child or the parent app?)

**Comment by faassen** [comment]
@href, opinions please? I had in my head that this ought to work for link generation but there is something to say for controlling this globally.

Do we need two prefix mechanisms, one global and one per app, with second second overriding the first? I need to consider the implementation as I don't yet understand why it works globally.

**Comment by href** [comment]
The earliest I can look at this is by the end of next week. The conference I'm co-organising is tomorrow ;)

**Comment by href** [comment]
In my opinion this is a bug. The link_prefix code never took mounted applications into account. The referenced commit/pull request fixes this issue. Please let me know what you think @faassen.

Also thank you @inytar for reporting this issue. I took the liberty of including your code as a test-case.

**Comment by henri-hulski** [comment]
Seems to be fixed.
