### ISSUE TITLE
render_json pretty print

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#82]
See jsonify in flask:

https://github.com/mitsuhiko/flask/blob/master/flask/json.py#L201

It looks at a config setting and pretty prints the json (if not handling an xml-http request). This would be nice to have for Morepath, but will have to await a config system. It implies that render_json and thus render will at least need to grow aware of the current lookup so that the config can be accessed. Perhaps it should have access to the request, then. This changes the signature of render functions, which will break the API unless we use mapply to put the request in. Putting this in for 0.1 anyway, at least the signature change. (also needs a doc update)

**Comment by href** [comment]
I encountered this today and I'm interested in implementing it. For my use case I'm looking for a way to always pretty print certain paths, while other paths should not be pretty printed (in my project I have a mix of internal JSON apis and public open data urls).

So I was thinking if it would make sense to just add this to the json directive? For example:

```python
@App.json(model=Document, pretty=True)
def view_document(self, request):
    return self
```

**Comment by webmaven** [comment]
Hmm. If `pretty` defaults to `True`, can it be overridden to `False` by the client?

**Comment by faassen** [comment]
I feel we should explore making this a tween. I realize it does not do fine
grained control but this makes me curious about the use cases for this
feature. What is your use case?

**Comment by href** [comment]
> Hmm. If pretty defaults to True, can it be overridden to False by the client?

I'm not sure I understand your comment. I meant that pretty should be the exception, not the default.

> What is your use case?

I have a web app showing election results in Switzerland. Part of the app uses JSON for D3.js map display, another part provides the results as JSON export as part of an open data initiative. 

I don't care how the JSON for the map looks like, but I would like to output the open data in a readable way, so humans can inspect it.

I would argue that putting this parameter close to the view not only makes it flexible and easy to implement, it also lets you know right there on the view, how the output is going to look like.

A global option is not something one might be aware of when looking at the function.

**Comment by faassen** [comment]
So the use case is that you have a separate web service that exposes open data and it needs to be inspectable by humans (without the benefit of browser development tools). This is different from a debugging use case where you'd want to turn it on globally temporarily when you develop. (though with dev tools this use case is not very strong).

One way to do this would be to implement your own renderer that renders pretty printed JSON (very similar to `render_json`, so a `render_json_pretty`) and use this. We could include it in Morepath and document this? Would this be really much harder to use than `pretty=True`? We could also pretty easily create a new directive that uses this new renderer, though that seems overkill for Morepath itself.

Another way to think about it is to say the whole open data web service is a separate app and pretty printing is somehow configurable for this app. But I can't think of the right way to do this now - a tween would apply to all applications, so doesn't fit. We could implement a hook but I'd prefer not to have a hook that does this determination during runtime.


I think it would actually be nice in this case to configure this globally per app: you could then create an open data Morepath

**Comment by href** [comment]
I also think adding another directive like this is overkill. So I'm +1 with adding this as a global option. I can really just activate it for the whole application as well. With gzip there's hardly any measurable difference in response size.

**Comment by faassen** [comment]
A global option can take the form of a tween that does it. It's slightly less efficient as it'll have to parse and reserialize the JSON. But this doesn't really need to be part of Morepath itself at all; could be an extension. Concerning a custom render_json_pretty, wouldn't that work for you? It's only a little bit more cumbersome than a `pretty=True` to type but this isn't a very common use case I expect.

**Comment by href** [comment]
> Concerning a custom render_json_pretty, wouldn't that work for you? It's only a little bit more cumbersome than a pretty=True to type but this isn't a very common use case I expect.

Yeah sorry I forgot to mention that. That makes sense for me to include in my specific project.

This kind of leaves this ticket at a point where we can close it no? Because I agree that we don't *need* this in morepath.

Once I have my renderer I can link to it here so if someone else needs this there's an example.

**Comment by webmaven** [comment]
So, which should be the canonical (and documented) solution?:
- a global option in the form of a tween (whether included or extra)
- a custom `render_json_pretty`
